CODE_OF_CONDUCT.md
Maybe this should have been in the initial commit, but better "late"
than never.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1)
=> Adopt a code of conduct for the repository.

.bazelrc, ci/kokoro/build-docker.sh, ci/kokoro/docker/asan-presubmit.cfg, ci/kokoro/docker/asan.cfg, ci/kokoro/docker/build.sh, ci/kokoro/docker/tsan-presubmit.cfg, ci/kokoro/docker/tsan.cfg, ci/kokoro/docker/ubsan-presubmit.cfg, ci/kokoro/docker/ubsan.cfg
Enable a build with AddressSanitizer, a build with ThreadSanitizer,
and one with UndefinedBehaviorSanitizer.
Fixes #5 and fixes #6.
=> Configure sanitizer builds.

google/cloud/spanner/value.h, google/cloud/spanner/value_test.cc
(Note: this was mostly pair programmed with @devbww )
Fixes #68
modified:   value_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/69)
=> Adds support for optional<T>.

ci/kokoro/Dockerfile.fedora-install, cmake/external/google-cloud-cpp.cmake, google/cloud/spanner/spanner_tool.cc
Use the version of google-cloud-cpp that has the right googleapis.
Fix a couple of TODOs in the spanner tool, mostly to show that we do
have a version of googleapis suitable to compile Spanner.
=> Update googleapis for CMake.

ci/kokoro/docker/build.sh
Much easier to document what these arguments are for.
=> Use an array for the `docker run` arguments.

ci/kokoro/docker/gcc-4.8-presubmit.cfg, ci/kokoro/docker/gcc-4.8.cfg
I missed these files in the last PR.
=> Add Kokoro config files.

ci/kokoro/docker/upload-docs.sh
My initial approach to detect the branch in the Kokoro build was too
naive. Kokoro checks out the code in `detached HEAD` mode, that is,
the HEAD commit is not associated with any branch. And Kokoro does not
expose the branch name in an environment variable, as other CI systems
do. And the git version on Kokoro does not support
`git branch --short-current`.
In this PR we guess (or detect depending on how confident you feel) the
branch by looking at the current commit, finding out which branches
contain it, and then doing some filtering.
I also fixed some nits in the shell style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/108)
=> Discover the actual branch in Kokoro.

ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh, ci/kokoro/docker/coverage-presubmit.cfg, ci/kokoro/docker/coverage.cfg
Without this we are not going to know if the integration tests actuall
test what we need them to.
=> Run integration tests in code coverage build.

google/cloud/spanner/row.h, google/cloud/spanner/row_test.cc
=> Implement relational ops for spanner::Row

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_tool.cc
This version of DatabaseAdminClient provides (I think) the API we want,
but the implementation is very naive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/125)
=> feat: Implement skeleton for DatabaseAdminClient.

google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h
This was a discussion with @mr-salty, we agreed to make these pure
virtual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/133)
=> cleanup: DatabaseAdminStub functions are pure virtual.

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/Dockerfile.fedora-install, cmake/external/google-cloud-cpp.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/139)
=> Updates version of google-cloud-cpp dep.

google/cloud/spanner/database_admin_client.h
I completely forgot to document the class and the first few functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/134)
=> doc: Fix documentation for DatabaseAdminClient.

google/cloud/spanner/sql_statement.cc, google/cloud/spanner/sql_statement.h, google/cloud/spanner/sql_statement_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/140)
=> feat: Added parameter support

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/internal/spanner_stub.cc, google/cloud/spanner/internal/spanner_stub.h, google/cloud/spanner/internal/spanner_stub_test.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
gRPC/GAPIC-like wrapper for the Spanner API.
Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/130)
=> feat: Implement skeleton SpannerStub

google/cloud/spanner/database_admin_client.cc
Sometimes the test function would exit before the (detached) thread running
the polling loop terminates. The thread is holding a `std::shared_ptr<>` to
the mock object, and the mocking framework would complain that the mock
was not deleted. As a matter of fact, the mock would be deleted shortly
after, when the detached thread did exit, but the mocking framework does
not know that.
In this PR we release the (mock or not) stub as soon as we no longer
need it. That removes the bug and also saves resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/148)
=> bug: Fix flake in DatabaseAdminClient unit test.

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/Dockerfile.fedora-install, cmake/external/google-cloud-cpp.cmake
Updating to pickup support for StatusOr<T> equality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/158)
=> chore: Update google-cloud-cpp dep version.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/row_parser.h, google/cloud/spanner/row_parser_test.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
Fixes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/171)
=> Add RowParser

google/cloud/spanner/row.h, google/cloud/spanner/value.h
Changed to using @code, @par, @note, @warning, etc.
Inspected doxygen output and iterated until it looked slightly better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/173)
=> Improved some doxygen commenting.

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_retry.cc, google/cloud/spanner/internal/database_admin_retry.h, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/samples/database_admin_samples.cc
With this PR developers can update a database schema, they can create
more tables, alter tables, drop tables, etc.
Fixes #178 and fixes #179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/203)
=> feat: Implement DatabaseAdmin::UpdateDatabase.

.gitignore, ci/kokoro/bazel-dependency/linux/build.sh, ci/kokoro/bazel-dependency/linux/continuous.cfg, ci/kokoro/bazel-dependency/linux/presubmit.cfg, ci/test-install/BUILD, ci/test-install/WORKSPACE
This is basically lifted from google-cloud-cpp with minor modifications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/219)
=> feat: Add build for testing spanner as a bazel dependency.

google/cloud/spanner/sql_statement.h, google/cloud/spanner/sql_statement_test.cc
Fixes #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/216)
=> Add equality operators to SqlStatement class

.dockerignore
This makes the install builds go faster when running them on your
workstation, I expect no effect for the CI environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/204)
=> chore: Speedup install builds.

google/cloud/spanner/row_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/227)
=> chore: Add unit test to show that `Row` works with nulls (unset optionals)

google/cloud/spanner/mutations.h, google/cloud/spanner/mutations_test.cc
This is part for the work for #198.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/223)
=> feat: Implement InsertOrUpdate and Replace mutations.

google/cloud/spanner/database_admin_client.h, google/cloud/spanner/samples/CMakeLists.txt, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/samples/spanner_client_samples.bzl
Fixes #187 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/229)
=> Add a sample for creating a struct with data

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/Dockerfile.fedora-install, ci/kokoro/install/Dockerfile.fedora, cmake/external/google-cloud-cpp.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/240)
=> chore: Update google cloud cpp version

.gitignore
Some recently added files are showing as "ignored", so don't ignore them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/243)
=> cleanup: Tweak .gitignore file.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/result_set.h, google/cloud/spanner/result_set_test.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
Initial implementation for `ResultSet`.
Fixes #65.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/221)
=> feat: implement `ResultSet`.

google/cloud/spanner/value.cc, google/cloud/spanner/value.h, google/cloud/spanner/value_test.cc
Fixes #52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/257)
=> feat: Added Value::Bytes support

google/cloud/spanner/internal/transaction_impl.h, google/cloud/spanner/internal/transaction_impl_test.cc
Use "google/cloud/internal/port_platform.h" to enhance portability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/266)
=> Migrate from __EXCEPTIONS to GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/commit_result.h, google/cloud/spanner/spanner_client.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/269)
=> Add a CommitResult type.

ci/kokoro/docker/build-in-docker-cmake.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/280)
=> testing: Run integration tests in parallel

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
Fixes #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/276)
=> feat: Skeleton for spanner::Client

google/cloud/spanner/client.cc
This comment is intended for *us*, not for customers, so I think it would be useful to have in the .cc file as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/282)
=> Added warning not to work on BatchDML until after Alpha. [skip ci]

google/cloud/spanner/client.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/290)
=> fixed indenting

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/295)
=> Supply the database name when creating a Client.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/date.cc, google/cloud/spanner/date.h, google/cloud/spanner/date_test.cc, google/cloud/spanner/spanner_client.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/275)
=> Add normalization to `google::cloud::spanner::Date`

.gitignore, ci/kokoro/macos/build-bazel.sh, ci/kokoro/macos/build-cmake.sh, ci/kokoro/macos/build.sh, ci/kokoro/macos/common.cfg
Create driver scripts for macOS and Bazel. In this initial version
the integration tests are not executed. That will happen in a future
PR.
This commit also includes a draft script to build with CMake, but it
does not work yet. Or more accurately, we need to create at least
one .o file in the `spanner_client_testing` library before it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/297)
=> feat: Create configuration for macOS+Bazel build.

ci/kokoro/macos/build-bazel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/308)
=> cleanup: Fix shellcheck warning.

google/cloud/spanner/row.h
See also: https://github.com/googleapis/google-cloud-cpp-spanner/issues/21#issuecomment-519233872
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/324)
=> fix: Add a ref-qualifier for correct overload

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/windows/bazel/build.bat, ci/kokoro/windows/bazel/common.cfg
Now it just builds the project. Unit tests and integration tests will come in a later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/326)
=> testing: Add Windows Bazel build

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/keys.h, google/cloud/spanner/keys_test.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/spanner_client_unit_tests.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/327)
=> feat: Add a stub `KeySet` class.

google/cloud/spanner/keys.h, google/cloud/spanner/keys_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/317)
=> feat: add KeyRange and KeySet classes

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/330)
=> docs: Add a badge for Windows Bazel build

google/cloud/spanner/sql_statement.cc, google/cloud/spanner/sql_statement.h, google/cloud/spanner/sql_statement_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/335)
=> Add a ToProto() method for SqlStatement.

google/cloud/spanner/internal/partial_result_set_reader_test.cc
(from Greg's comment on another PR)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/336)
=> remove unnecessary explicit types from this test.

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/connection.h, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
Fixes #289.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/338)
=> feat: Implement Client::Rollback()

google/cloud/spanner/client.cc, google/cloud/spanner/client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/345)
=> Remove KeySet placeholder in favor of the real thing

.clang-tidy, google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Also made the test a little faster by creating the database only once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/361)
=> feat: Add integration test for DeleteMutation.

google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Use a single `Client` (which implies a single session) of all the
MutateAndReadIntegrationTest cases. This reduces the test startup/
teardown costs immensely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/368)
=> refactor: Single client for all MutateAndReadIntegrationTest cases

google/cloud/spanner/keys.cc, google/cloud/spanner/keys.h, google/cloud/spanner/keys_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/365)
=> feat: add KeySet equality operators and constructor from proto

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Fixes #356.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/358)
=> Implement spanner::RunTransaction() skeleton

google/cloud/spanner/integration_tests/client_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/376)
=> feat: Implement integration tests for ExecuteSql.

google/cloud/spanner/samples/samples.cc
Fixed #182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/378)
=> feat: Add dml_standard_insert sample code.

google/cloud/spanner/samples/samples.cc
This sample populates the tables used in all the other samples, seems
sensible to add it ASAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/381)
=> feat: Implement spanner_insert_data sample.

google/cloud/spanner/samples/samples.cc
Fixes #377
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/383)
=> cleanup: Share spanner::Client across samples.

google/cloud/spanner/samples/samples.cc
Fixes #183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/385)
=> feat: Implement spanner_dml_standard_update sample.

google/cloud/spanner/samples/samples.cc
- Move DmlStandardInsert() namespace alias inside function.
- Change DmlStandardUpdate() namespace alias to "spanner".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/393)
=> Namespace tweaks for samples

google/cloud/spanner/samples/samples.cc
Add samples that use DML to delete some data
(spanner_dml_standard_delete) an use mutations to delete data by key and
ranges (spanner_delete_data).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/396)
=> feat: implement delete samples.

google/cloud/spanner/internal/partial_result_set_reader.cc, google/cloud/spanner/internal/partial_result_set_reader.h, google/cloud/spanner/internal/partial_result_set_reader_test.cc
Fixes #270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/394)
=> Support chunked_value reassembly.

google/cloud/spanner/samples/samples.cc
This fixes #188 and fixes #189. I moved the code around to put all the 'STRUCT' samples together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/399)
=> feat: implement query_data_with_struct sample.

google/cloud/spanner/samples/samples.cc
Also improve logging to troubleshoot build failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/403)
=> cleanup: Refactor common code in samples.

google/cloud/spanner/samples/samples.cc
Fixes #190.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/402)
=> feat: Implement query_data_with_array_of_struct sample.

google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/samples/samples.cc
Use a simple `SELECT` as the quickstart program. Also change the region
tags so the quickstart program with have the minimal `#include`
statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/405)
=> feat: A simpler quickstart program.

ci/generate-badges.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/410)
=> cleanup: fix a shellcheck warning.

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/connection.h, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/read_partition.cc, google/cloud/spanner/read_partition.h, google/cloud/spanner/transaction.cc, google/cloud/spanner/transaction.h
fixes #346 
fixes #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/408)
=> feat: implement PartitionRead and Read(ReadPartition)

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
Fixes #423.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/406)
=> bug: Make internal::ConnectionImpl thread-safe.

google/cloud/spanner/testing/matchers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/473)
=> Fix a header nit (cstdint vs cinttypes)

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/batch_dml_result.h, google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc, google/cloud/spanner/connection.h, google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/spanner_client.bzl
Fixes #459 and fixes #431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/501)
=> feat: add Client::ExecuteBatchDml() with integration test

ci/kokoro/windows/bazel/build.bat, google/cloud/spanner/connection_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/475)
=> test: Run unit tests on windows bazel build

google/cloud/spanner/client.cc, google/cloud/spanner/client.h, google/cloud/spanner/client_test.cc
Apparently errors in quick succession are common, and the recommended
practice is to limit the number of failures based on a time limit rather
than a count. This PR changes `RunTransaction` to use a
`LimitedTimeRetryPolicy` by default. This change also refactors
`RunTransaction` to `internal::RunTransactionWithPolicies` so our tests
can verify the function runs without having to wait for multiple seconds
(or minutes).
This fixes #508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/510)
=> bug: RunTransaction uses a time-based retry policy.

google/cloud/spanner/integration_tests/client_integration_test.cc
The integration test for `Client::Rollback()` flakes and cannot use
RunTransaction(). This change runs the part of the test that has been
flaky in a custom loop, and then calls `Rollback()` explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/513)
=> bug: make rollback test less flaky.

google/cloud/spanner/integration_tests/client_integration_test.cc
Address post-merge comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/528)
=> cleanup: improve rollback integration test.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/spanner_client_testing.bzl, google/cloud/spanner/testing/mock_database_admin_stub.h
Need to mock the DatabaseAdminStub in more than one test, refactor out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/532)
=> cleanup: refactor MockDatabaseAdminStub.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/internal/log_wrapper.h, google/cloud/spanner/internal/logging_spanner_stub.cc, google/cloud/spanner/spanner_client.bzl
We are going to need these helpers to log from DatabaseAdminClient, and
eventually from InstanceAdminClient too.  This change just refactors
them to a separate file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/531)
=> cleanup: refactor logging helpers.

ci/kokoro/windows/bazel/build.bat, ci/kokoro/windows/bazel/common.cfg
fixes #21 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/526)
=> test: Run integration tests on Windows Bazel builds

google/cloud/spanner/client.h, google/cloud/spanner/keys.h, google/cloud/spanner/query_partition.h, google/cloud/spanner/read_partition.h, google/cloud/spanner/samples/samples.cc
fixes #328 
fixes #388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/503)
=> chore: add samples for keyset, partition read, and partition query

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/database_admin_retry.cc, google/cloud/spanner/internal/database_admin_retry.h, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/internal/range_from_pagination.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/spanner_client.bzl, google/cloud/spanner/testing/mock_database_admin_stub.h
Add the function in the client, stub (and the stub decorators), the
corresponding unit tests, use the function in the integration tests, and
an example.
This fixes #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/543)
=> feat: implement DatabaseAdminClient::ListDatabases.

cmake/EnableDoxygen.cmake, google/cloud/spanner/row.h
Fixes #559 and fixes #554.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/568)
=> doc: document GetElement<I>(Row).

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_retry.cc, google/cloud/spanner/internal/database_admin_retry.h, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_database_admin_stub.h
Implement the function, the usual unit tests, use the function as part
of the integration test for CRUD operations, and add an example.
This fixes #206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/564)
=> feat: implement DatabaseAdminClient::GetDatabase.

google/cloud/spanner/internal/connection_impl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/563)
=> Return PartitionedDml sessions to the pool.

cmake/EnableDoxygen.cmake, google/cloud/spanner/doc/spanner-mocking.dox, google/cloud/spanner/mocks/mock_instance_admin_connection.h, google/cloud/spanner/mocks/mock_spanner_connection.h
Fixes #553, fixes #551, and fixes #549.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/575)
=> doc: Document the mocks and exclude testing types.

google/cloud/spanner/samples/samples.cc
I am not sure how, but I botched a rebase/merge in #489, I remember
removing this debugging code, but it is clearly there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/574)
=> cleanup: fix botched rebase.

google/cloud/spanner/row.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/581)
=> doc: fix typo in Doxygen comment

google/cloud/spanner/polling_policy.h
Fixes #546 and fixes #548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/583)
=> doc: document polling classes.

google/cloud/spanner/samples/samples.cc, google/cloud/spanner/sql_statement.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/576)
=> chore: added documentation and snippet for SqlStatement

google/cloud/spanner/connection.h
Fixes #562 and fixes #544.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/587)
=> doc: document spanner::Connection class members.

google/cloud/spanner/instance_admin_connection.h
Fixes #560 and fixes #547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/588)
=> doc: fill in documentation for spanner::InstanceAdminConnection.

google/cloud/spanner/batch_dml_result.h
Fixes #545
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/590)
=> fix: Documents BatchDmlResult::Stats

google/cloud/spanner/transaction.h
Fixes #552.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/589)
=> doc: document MakeRead{Only,Write}Transaction functions

google/cloud/spanner/client.h, google/cloud/spanner/keys.h, google/cloud/spanner/read_partition.h, google/cloud/spanner/result_set.h
fixes #558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/591)
=> remove TODOs from public headers

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_retry.cc, google/cloud/spanner/internal/database_admin_retry.h, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_database_admin_stub.h
Fixes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/594)
=> feat: implement DatabaseAdminClient::GetDatabaseDdl.

google/cloud/spanner/instance_admin_client.cc, google/cloud/spanner/instance_admin_client.h, google/cloud/spanner/instance_admin_client_test.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/internal/instance_admin_retry.cc, google/cloud/spanner/internal/instance_admin_retry.h, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/mocks/mock_instance_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_instance_admin_stub.h
The first of the IAM-related functions. This change also includes the
unit test, the integration test, and the example.
Fixes #524.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/597)
=> feat: implement InstanceAdminClient::TestIamPermissions.

google/cloud/spanner/backoff_policy.h, google/cloud/spanner/connection.h, google/cloud/spanner/connection_options.h, google/cloud/spanner/instance_admin_client.h, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/mutations.h, google/cloud/spanner/query_partition.h, google/cloud/spanner/read_partition.h, google/cloud/spanner/retry_policy.h, google/cloud/spanner/row.h, google/cloud/spanner/sql_statement.h, google/cloud/spanner/value.h
Mostly just adding/removing blank lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/602)
=> chore: minor header cleanup.

google/cloud/spanner/connection_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/603)
=> fix: changed getter return to const-ref

ci/kokoro/windows/common.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/608)
=> test: Disable integration tests in Windows CMake builds

README.md, ci/generate-badges.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/610)
=> feat: Add a badge for Windows CMake build

ci/kokoro/windows/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/612)
=> fix: Use correct URL for google-cloud-cpp

google/cloud/spanner/instance_admin_client.cc, google/cloud/spanner/instance_admin_client.h, google/cloud/spanner/instance_admin_client_test.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/internal/instance_admin_retry.cc, google/cloud/spanner/internal/instance_admin_retry.h, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/mocks/mock_instance_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_instance_admin_stub.h
Add the function, the usual integration test, unit tests, and a simple
example.
Fixes #523.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/609)
=> feat: implement InstanceAdminClient::GetIamPolicy

ci/kokoro/docker/publish-refdocs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/626)
=> docs:Run pyenv for docuploader

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/635)
=> docs: Change doxygen URL to googleapis.dev

ci/kokoro/docker/build.sh, ci/kokoro/docker/publish-refdocs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/634)
=> docs:Upgrade python-protobuf for docuploader

google/cloud/spanner/samples/samples.cc
Fixes #616.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/654)
=> bug: use RunTransaction for read write transaction sample

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/spanner_client_unit_tests.bzl
Fixes #419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/655)
=> cleanup: split tests for DatabaseAdmin{Client,Connection}

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc
Add retry policy and backoff policy member functions to
`internal::ConnectionImpl`, then change the Rollback() member function
to use the retry loop, and change the tests to verify it does retry
a single failure, it stops on the first permanent failure, and that it
stops retrying when there are too many transient failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/657)
=> feat: implement retry loop for ConnectionImpl::Rollback

doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/640)
=> docs: Add a section for publishing docs in the release process

google/cloud/spanner/database_admin_client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/662)
=> fix: Fix sample code in the comment

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
Fixes #660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/661)
=> feat: wrap CreateSession in a retry loop

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
Fixes #647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/663)
=> feat: add retry loop to ExecuteBatchDml

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/mocks/mock_database_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_database_admin_stub.h
fixes #209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/670)
=> feat: implement DatabaseAdminClient::GetIamPolicy.

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/mocks/mock_database_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_database_admin_stub.h
fixes #208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/672)
=> feat:Implement DatabaseAdminClient::SetIamPolicy.

google/cloud/spanner/database_admin_client.cc, google/cloud/spanner/database_admin_client.h, google/cloud/spanner/database_admin_client_test.cc, google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/integration_tests/database_admin_integration_test.cc, google/cloud/spanner/internal/database_admin_logging.cc, google/cloud/spanner/internal/database_admin_logging.h, google/cloud/spanner/internal/database_admin_logging_test.cc, google/cloud/spanner/internal/database_admin_metadata.cc, google/cloud/spanner/internal/database_admin_metadata.h, google/cloud/spanner/internal/database_admin_metadata_test.cc, google/cloud/spanner/internal/database_admin_stub.cc, google/cloud/spanner/internal/database_admin_stub.h, google/cloud/spanner/mocks/mock_database_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_database_admin_stub.h
fixes #210
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/673)
=> feat: implement DatabaseAdminClient::TestIamPermissions.

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/668)
=> feat: implement retry loop for PartitionQuery

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
This fixes #645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/669)
=> feat: implement retry for PartitionRead

google/cloud/spanner/internal/instance_admin_logging.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/677)
=> fix: Fix the doc comment.

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
Fixes #648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/680)
=> feat: implement retry loop for Commit()

google/cloud/spanner/instance_admin_client.cc, google/cloud/spanner/instance_admin_client.h, google/cloud/spanner/instance_admin_client_test.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/internal/instance_admin_logging.cc, google/cloud/spanner/internal/instance_admin_logging.h, google/cloud/spanner/internal/instance_admin_logging_test.cc, google/cloud/spanner/internal/instance_admin_metadata.cc, google/cloud/spanner/internal/instance_admin_metadata.h, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/mocks/mock_instance_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_instance_admin_stub.h
fixes #516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/682)
=> feat: implement InstanceAdminClient::GetInstanceConfig.

google/cloud/spanner/instance_admin_client.cc, google/cloud/spanner/instance_admin_client.h, google/cloud/spanner/instance_admin_client_test.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/internal/instance_admin_logging.cc, google/cloud/spanner/internal/instance_admin_logging.h, google/cloud/spanner/internal/instance_admin_logging_test.cc, google/cloud/spanner/internal/instance_admin_metadata.cc, google/cloud/spanner/internal/instance_admin_metadata.h, google/cloud/spanner/internal/instance_admin_metadata_test.cc, google/cloud/spanner/internal/instance_admin_stub.cc, google/cloud/spanner/internal/instance_admin_stub.h, google/cloud/spanner/mocks/mock_instance_admin_connection.h, google/cloud/spanner/samples/samples.cc, google/cloud/spanner/testing/mock_instance_admin_stub.h
fixes #515 
We might not like the order of the functions, in that case I will change the order with another PR (doing so at the same time makes the diff terrible).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/683)
=> feat: implement InstanceAdminClient::ListInstanceConfigs.

google/cloud/spanner/instance_admin_connection.h
s/Connection/InstanceAdminConnection/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/687)
=> cleanup: Fix typp

google/cloud/spanner/mocks/mock_spanner_connection.h, google/cloud/spanner/query_partition.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/685)
=> chore: prepare the code for import to google.

README.md
Changed "APIS" to "APIs".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/917)
=> Fixes minor typo.

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/integration_tests/CMakeLists.txt, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, google/cloud/spanner/testing/random_instance_name.cc
fixes #918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/919)
=> test: add cleanup code for deleting leaked temporary instances

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc
Part of #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/924)
=> Use BatchCreateSessionsRequest to create sessions.

google/cloud/spanner/integration_tests/throughput_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/945)
=> chore: Fix google import by renaming `spanner` namespace.

doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/949)
=> doc: linkify the link to generated documentation

google/cloud/spanner/samples/samples.cc
We need to return a `StatusOr<>` from the helper lambda, and check its
value, otherwise the `RunTransaction` loop stops on the first exception.
I think this fixes #953.  I ran it 50 times on my workstation without a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/956)
=> bug: fix flakes in read_write_transaction sample

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/957)
=> chore: added compile_commands.json to gitignore

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/958)
=> testing: add a badge for bazel-ci build

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/964)
=> refactor: change all *Params variables to `params`

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/966)
=> doc: fix link in Bazel CI badge

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/mutations.h, google/cloud/spanner/row.cc, google/cloud/spanner/row.h, google/cloud/spanner/row_parser.h, google/cloud/spanner/row_test.cc, google/cloud/spanner/spanner_client.bzl
Part of #387 
This PR adds the `Row` class that will be used by #387. This class is added and tested in this PR, but it is not used yet. This is an attempt to break up a large PR into smaller PRs. So this PR just adds the class. A subsequent PR will start using this type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/968)
=> feat: adds Row class, not yet used

google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl_test.cc
fixes #644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/979)
=> feat: add retry functionality and tests for ExecutePartitionedDml

google/cloud/spanner/client.h, google/cloud/spanner/samples/samples.cc
Fixes: #493
This sample also shows how to use `SELECT *`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/984)
=> feat: implements spanner_query_data sample

google/cloud/spanner/connection.h
Fixes: #985
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/990)
=> docs: fixed connection.h docs to reference Client rather than RPCs

google/cloud/spanner/integration_tests/spanner_install_test.cc
Fixes #946.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/991)
=> bug: skip non-testing instances in install test

ci/etc/kokoro/install/project-config.sh, ci/etc/kokoro/install/run-installed-programs.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-trusty, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/install/build.sh
This is the first set of automatically generated files for
ci/kokoro/install. Note that this adds the configuration for several
builds, but these builds are not yet enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/988)
=> ci: automatically generate ci/kokoro/install

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/999)
=> chore: add feature template; update bug template

.github/ISSUE_TEMPLATE/bug_report.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1002)
=> chore: correct "about" text in bug-report template

ci/test-readme/generate-readme.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1008)
=> style: quash some shell lint

google/cloud/spanner/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1024)
=> chore: update README

google/cloud/spanner/samples/samples.cc
fixes #479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1020)
=> feat: add spanner_create_index example

google/cloud/spanner/samples/samples.cc
fixes #480
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1029)
=> feat: implement spanner_create_storing_index example

google/cloud/spanner/samples/samples.cc
Fixes #500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1031)
=> feat: added spanner_read_stale_data sample

google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/internal/connection_impl.cc, google/cloud/spanner/internal/connection_impl.h, google/cloud/spanner/internal/partial_result_set_resume.cc, google/cloud/spanner/internal/partial_result_set_resume.h, google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1028)
=> cleanup: explicitly name Policies used as prototypes

google/cloud/spanner/integration_tests/CMakeLists.txt, google/cloud/spanner/integration_tests/single_row_cpu_benchmark.cc, google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
Fixes #1013 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1025)
=> feat: implement scaffolding for CPU benchmarks

google/cloud/spanner/samples/samples.cc
fixes #482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1036)
=> feat: implement spanner_create_table_with_timestamp_column sample

google/cloud/spanner/samples/samples.cc
fixes #1038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1040)
=> refactor: share admin client objects within samples

google/cloud/spanner/connection_options_test.cc
Remove another flaky test for the background threads and change the
existing test to not depend on timing, but on the order of operations.
Fixes #1032.  I ran the remaining test 1000 times without flakes on my
workstation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1046)
=> bug: reduce test flakiness

google/cloud/spanner/samples/samples.cc
fixes #497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1049)
=> feat: implement spanner_read_data example

google/cloud/spanner/internal/partial_result_set_source.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1052)
=> chore: attempt to speed up hot loop in NextRow

google/cloud/spanner/samples/samples.cc
fixes #499 
I'm using `google::cloud::optional` for handling nullable int64 field. It seems working, but is it an correct expected usage?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1055)
=> feat: implement the spanner_read_data_with_storing_index example

google/cloud/spanner/samples/samples.cc
fixes #498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1059)
=> feat: implement the spanner_query_with_parameter example

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1064)
fixes #495
=> feat: implement the spanner_query_data_with_new_column example

google/cloud/spanner/samples/samples.cc
fixes #494
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1065)
=> feat: implement the spanner_query_data_with_index example

google/cloud/spanner/doc/spanner-main.dox, google/cloud/spanner/samples/samples.cc
Fixes: #245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1066)
=> doc: add example showing how to use StatusOr

google/cloud/spanner/results.h, google/cloud/spanner/samples/samples.cc
Fixes: #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1068)
=> docs: adds sample for spanner_dml_struct

google/cloud/spanner/samples/samples.cc
Fixes: #1070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1071)
=> doc: add spanner_add_timestamp_column

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1072)
=> refactor: reduce code duplication in samples

google/cloud/spanner/samples/samples.cc
Fixes: #487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1073)
=> doc: add spanner_dml_standard_update_with_timestamp

.gitignore, google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
To be fair, also separate the response via stubs into "rows", and fix some problems
with session setup on the Stub case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1076)
=> feat: change CPU benchmark to use multiple columns

google/cloud/spanner/samples/samples.cc
fixes #478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1080)
=> doc: implement spanner_batch_client example

google/cloud/spanner/samples/samples.cc
fixes #492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1078)
=> doc: implement the spanner_dml_write_then_read example

google/cloud/spanner/samples/samples.cc
Fixes: #485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1075)
=> doc: add 'transfer money' example

google/cloud/spanner/database_admin_connection.cc, google/cloud/spanner/instance_admin_connection.cc, google/cloud/spanner/internal/connection_impl.cc
Fixes: #177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1086)
=> refactor!: drop support for compile-time preprocessor config

google/cloud/spanner/internal/background_threads_test.cc
I missed this before, another place where we need to activate the
completion queue later so the test does not flake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1087)
=> bug: fix another flaky test

google/cloud/spanner/samples/samples.cc
fixes #483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1081)
=> doc: implement the spanner_dml_batch_update example

INSTALL.md, ci/test-readme/generate-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1093)
=> doc: update the INSTALL instructions

google/cloud/spanner/integration_tests/data_types_integration_test.cc, google/cloud/spanner/testing/database_environment.cc
Part of #1096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1100)
=> feat: added DataType integration test for arrays

google/cloud/spanner/benchmarks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1090)
=> doc: add README for the benchmarks

google/cloud/spanner/integration_tests/data_types_integration_test.cc
Fixes #1096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1102)
=> feat: add datatype integration test for struct

google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Fixes #1012
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1107)
=> feat: benchmark UPDATE and SELECT for a single row

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Run the smoke tests in parallel to keep the CI build times under
control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1115)
=> feat: parallelize benchmark smoke tests

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Fixes #1014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1123)
=> feat: benchmark CPU overhead for mutations

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
This fixes #1018.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1116)
=> feat: benchmark CPU overhead for SELECT

google/cloud/spanner/integration_tests/client_integration_test.cc
Fixes: #1112
Fixes: #1113
Fixes: #1114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1127)
=> feat: add integration tests for profiling APIs

README.md, ci/test-readme/README.md.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1129)
=> chore: release notes for v0.4.0

INSTALL.md, ci/test-readme/README.md, ci/test-readme/generate-install.sh
fixes #1132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1135)
=> docs: fix generate-intall.sh

google/cloud/spanner/internal/session_pool.cc, google/cloud/spanner/internal/session_pool.h, google/cloud/spanner/internal/session_pool_test.cc
Fixes: #914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1142)
=> feat: delete bad sessions from pool

google/cloud/spanner/client_test.cc, google/cloud/spanner/connection_options_test.cc, google/cloud/spanner/database_admin_connection_test.cc, google/cloud/spanner/instance_admin_connection_test.cc, google/cloud/spanner/internal/connection_impl_test.cc, google/cloud/spanner/internal/polling_loop_test.cc
Fixes #1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1151)
=> cleanup: remove underscores from TEST names

ci/kokoro/windows/build-dependencies.ps1
fixes #1146 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1147)
=> testing: cleanup the buildtrees directory after each vcpkg builds

google/cloud/spanner/integration_tests/client_integration_test.cc
The integration test for `Client::Rollback()` was not retrying all
`ABORTED` errors.
Fixes #1023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1164)
=> bug: deflake rollback integration test

ci/kokoro/docker/check-api.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1165)
=> chore: disable shellcheck warning SC2043 for check_library loop

README.md, ci/test-readme/README.md.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1177)
=> chore: updating README preparing for release

README.md, ci/test-readme/generate-readme.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1178)
=> feat: beta release

google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1176)
=> fix: correct the order of columns

README.md, ci/test-readme/README.md.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1179)
=> fix: add date to v0.5.x release

README.md, ci/test-readme/README.md.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1184)
=> chore: release notes for 0.6 release

google/cloud/spanner/client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1173)
=> docs: tighten up some documentation for g:c:spanner::Client::Commit()

doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1188)
=> chore: update release instructions

bazel/googleapis.BUILD, ci/kokoro/dump-logs.sh, google/cloud/spanner/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1195)
=> fix: remove unnecessary dependency on bigtable

ci/kokoro/macos/build-bazel.sh, ci/kokoro/windows/bazel/build.bat
I missed these builds in the last PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1197)
=> ci: prevent flakes for Bazel + {macos,Windows}

doc/cutting-a-release.md
Related to Related to googleapis/google-cloud-cpp-spanner#1187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1206)
=> chore: remove instructions for file checksums

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1214)
=> doc: add spanner_create_user_defined_struct example

google/cloud/spanner/CMakeLists.txt, google/cloud/spanner/internal/merge_chunk_benchmark.cc, google/cloud/spanner/row_benchmark.cc, google/cloud/spanner/spanner_client_benchmarks.bzl
- `google/cloud/spanner/internal/merge_chunk_benchmark.cc`
- `google/cloud/spanner/row_benchmark.cc`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1221)
=> test: add a couple more micro benchmarks

google/cloud/spanner/samples/samples.cc
These examples show how to update and query timestamp columns, including
queries with NULL columns and inserting with the commit timestamp.
Fixes #1217, fixes #1218, and fixes #1219.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1223)
=> feat: implement query and update timestamp samples 

google/cloud/spanner/internal/range_from_pagination.h, google/cloud/spanner/mutations.h, google/cloud/spanner/testing/matchers.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1236)
=> chore: more header cleanup for enabling clang-tidy

google/cloud/spanner/internal/log_wrapper_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1249)
=> chore: expand some TAB indendation

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1272)
=> chore: update CHANGELOG.md for release

google/cloud/spanner/integration_tests/client_integration_test.cc, google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1276)
=> fix: make the allowances for emulator behavior more fine-grained

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1285)
=> fix: newline to tab

INSTALL.md, ci/test-readme/generate-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1291)
=> doc: fix typo in bazel bug link

INSTALL.md, ci/test-readme/generate-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1286)
=> fix: clone using https

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1294)
=> doc: tweak README for windows

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1298)
=> docs:change macOS roots.pem command to use curl

INSTALL.md
Fixes: #1297 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1304)
=> doc: fix example WORKSPACE docs

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1305)
=> fix: create "init_client" snippet for "Getting started" doc

CMakeLists.txt, ci/etc/kokoro/install/project-config.sh, ci/etc/kokoro/install/version-config.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh, cmake/EnableDoxygen.cmake
fixes #1301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1307)
I ran the `ci/templates/generate-kokoro-install.sh` in common and it didn't change anything.
=> docs: enable Doxygen cross link to g-c-c-common

google/cloud/spanner/client.h, google/cloud/spanner/samples/samples.cc
fixes #1300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1308)
=> docs: add example to client.h for ExecuteQuery using StreamOf

google/cloud/spanner/samples/README.md
Related to #1310 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1309)
=> doc: added samples/README.md

google/cloud/spanner/client.h, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1312)
=> docs: fix select query samples

google/cloud/spanner/client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1314)
=> chore: consistent whitespace usage for client.h

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1321)
=> doc: fix closing tag for spanner_delete_data

quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1323)
=> doc: document macOS workarounds

CHANGELOG.md, INSTALL.md, ci/test-readme/generate-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1324)
=> chore: update release notes

google/cloud/spanner/row.h, google/cloud/spanner/samples/samples.cc
Wrote a little example showing how to use it.
Fixes #1302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1327)
=> doc: an example of spanner::GetSingularRow

INSTALL.md, ci/kokoro/Dockerfile.ubuntu, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial
This ports similar changes from googleapis/google-cloud-cpp#3417. Thanks to @Rajpratik71 for providing the motivation and a template to follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1330)
=> ci: reduce Docker image size for Ubuntu+Debian

google/cloud/spanner/mutations.h, google/cloud/spanner/row.h, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1331)
=> doc: add more snippets to documentation

ci/kokoro/Dockerfile.fedora-install
Ooops, introduced bad typo in my last PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1333)
=> fix: correct typo in Dockerfile

ci/test-readme/generate-readme.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1337)
=> chore: remove unused code

quickstart/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1342)
=> cleanup: removed unneeded comment

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1348)
=> doc: link to the style guide in the common repo

quickstart/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1350)
=> chore: upgrade quickstart to Spanner v0.9.0 release

google/cloud/spanner/value_test.cc
Related to: #1347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1349)
=> chore: test proto values of NULL values

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/test-markdown/README.md, doc/packaging.md, super/external/googleapis.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1356)
=> chore: update cpp-cmakefiles version

ci/kokoro/Dockerfile.fedora-install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1357)
=> chore: update cpp-cmakefiles version for some builds

google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1368)
=> cleanup: removed unreachable code

google/cloud/spanner/samples/samples.cc
Also condense some other snippet pieces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1370)
=> cleanup: remove an unreachable throw statement

ci/kokoro/windows/build-bazel.ps1
Part of the work for googleapis/google-cloud-cpp-common#233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1375)
=> cleanup: fix warnings in ci scripts

ci/kokoro/windows/common.cfg
Part of the work for googleapis/google-cloud-cpp-common#227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1373)
=> ci: use powershell configuration file

ci/kokoro/windows/build-new.bat
Removing KOKORO_ARTIFACTS_DIR is failing, remove for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1378)
=> ci: troubleshoot new Windows+Bazel build

google/cloud/spanner/keys.h, google/cloud/spanner/mutations.h, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1394)
=> doc: update snippets for all mutation types

google/cloud/spanner/client.h, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1395)
=> doc: link existing example for ExecuteBatchDml

google/cloud/spanner/internal/polling_loop_test.cc
While looking at code uncovered by tests I noted that this test repeated
the same code several times, and it was code that was not supposed to be
reached. Refactored the function to a single place, less repetition, and
less untested code to confuse me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1402)
=> cleanup: simplify polling loop test

bazel/google_cloud_cpp_spanner_deps.bzl, ci/etc/kokoro/install/version-config.sh, ci/kokoro/Dockerfile.fedora-install, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL, ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake, doc/packaging.md, super/external/google-cloud-cpp-common.cmake
Part of the work for googleapis/google-cloud-cpp-common#248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1411)
=> chore: upgrade g-c-cpp-common to v0.24.0

ci/kokoro/Dockerfile.fedora-install, ci/kokoro/docker/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1413)
=> ci: use the correct distro version in the builds

google/cloud/spanner/samples/samples.cc
If the samples fail or timeout we need to have the latest sample in
the program output, or troubleshooting becomes harder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1420)
=> test: flush log before running each example

google/cloud/spanner/internal/polling_loop.h, google/cloud/spanner/internal/polling_loop_test.cc
Fixes #1426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1427)
=> fix: polling policy stops after 'too many' successes

google/cloud/spanner/doc/spanner-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1434)
=> fix: typo in dox

quickstart/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1436)
=> feat: change quickstart to use recommended build target

google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/instance_admin_connection.h, google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1440)
=> doc: snippets for admin clients with custom policies

google/cloud/spanner/internal/session_pool_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1445)
=> test: reduce running time of SessionPool.SessionRefresh (16s to 2s)

google/cloud/spanner/doc/spanner-main.dox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1448)
=> doc: add mention of GOOGLE_CLOUD_CPP_TRACING_OPTIONS env var

google/cloud/spanner/internal/session_pool.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1450)
=> cleanup: eliminate an unnecessary local variable

bazel/google_cloud_cpp_spanner_deps.bzl, ci/etc/kokoro/install/version-config.sh, ci/kokoro/Dockerfile.fedora-install, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/CONTROL, ci/kokoro/windows/vcpkg-ports/google-cloud-cpp-common/portfile.cmake, doc/packaging.md, super/external/google-cloud-cpp-common.cmake
Fixes #1457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1458)
=> chore: update g-c-cpp-common to v0.25.0

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1459)
=> chore: update CHANGELOG for release

bazel/google_cloud_cpp_spanner_deps.bzl, ci/kokoro/Dockerfile.fedora-install, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/windows/vcpkg-ports/googleapis/CONTROL, ci/kokoro/windows/vcpkg-ports/googleapis/portfile.cmake, doc/packaging.md, super/external/googleapis.cmake
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1469)
=> chore: update googleapis and cpp-cmakefiles deps to match -cpp

bazel/googleapis.BUILD, google/cloud/spanner/BUILD
Part of https://github.com/googleapis/google-cloud-cpp/issues/3838
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1470)
=> chore: simplify googleapis overlay BUILD

quickstart/CMakeLists.txt, quickstart/README.md
Fixes googleapis/google-cloud-cpp#3852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1477)
=> feat: support quickstart with Windows+CMake+Static builds

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1482)
=> doc: update release notes for v1.2.0

google/cloud/spanner/quickstart/WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1484)
=> chore: update version for */quickstart/WORKSPACE

google/cloud/spanner/database_admin_connection.h, google/cloud/spanner/update_instance_request_builder.h, google/cloud/spanner/value.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1485)
=> cleanup: fixed a few minor typos
