googleapis/google-cloud-cpp-spanner

- .clang-format
- .clang-tidy
- ci/check-include-guards.gawk
- ci/check-style.sh
- ci/colors.sh
- ci/define-dump-log.sh
- ci/install-bazel.sh
- ci/install-retry.sh
- ci/kokoro/Dockerfile.ubuntu
- ci/kokoro/build-docker.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/clang-tidy-presubmit.cfg
- ci/kokoro/docker/clang-tidy.cfg
- ci/kokoro/dump-logs.sh
- ci/kokoro/install-linux.sh
- ci/kokoro/linux-config.sh
- google/cloud/spanner/CMakeLists.txt
Setup one build on Kokoro, it runs clang-format (same version
as google-cloud-cpp), and clang-tidy. It also reformats CMake files
and BUILD files. I chose a newer version of the CMake formatter because
why not?
This is largely a cut&paste from the similar scripts in google-cloud-cpp, I think refactoring those scripts to a common place would be great, but it will take us a while to figure that out, and I believe we need to start making progress on the client library itself.
This is part of the work for #4, a separate CL inside google will enable this build and then we can close the work item.
> Enable one Kokoro build.

- ci/kokoro/build-docker.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/integration-presubmit.cfg
- ci/kokoro/docker/integration.cfg
- google/cloud/spanner/spanner_tool.cc
Change ci/kokoro scripts to (optionally) run integration tests.
Add a skeleton integration tests using the spanner tool.
> Enable integration test

- ci/kokoro/docker/build.sh
This keeps the script from failing when run locally, and
KOKORO_GFILE_DIR is not important in that case.
> Use /dev/shm as default KOKORO_GFILE_DIR

- WORKSPACE
- bazel/google_cloud_cpp_spanner_deps.bzl
- bazel/googleapis.BUILD
- google/cloud/spanner/BUILD
With the latest release of googleapis it is possible to disable Java and
Go dependencies.
> Simplify WORKSPACE file.

- ci/install-bazel.sh
- ci/kokoro/Dockerfile.ubuntu
- ci/kokoro/build-docker.sh
This makes local builds faster, because otherwise Bazel is installed
each time you run `BUILD_NAME=foo ./ci/kokoro/docker/build.sh`. It makes
little or no difference on the actual Kokoro builds.
> Install Bazel as part of the Docker image.

- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
closes #17 
This is just a skeleton of the class. It does not fully support all Spanner value types. Specifically it's missing
TIMESTAMP, DATE, BYTES, ARRAY, and STRUCT.
I will file separate GH issues to implement each of those separately.
(Note, I'm not actually working on a Saturday. I implemented this yesterday, but I wanted to trigger all the CI builds to see if this broke stuff.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/38)
> Implements spanner::Value skeleton with support for BOOL, INT64, FLOAT64, and STRING

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Removed the switch statement in operator==() in favor of a custom
protobuf message differencer, which will grow/expand with any
data/values that we stuff in the proto. A custom differencer was needed
so that we could make encoded "NaN" values still appear unequal to each
other, as they're supposed to.
Removed the switch statement in operator<<() and changed to directly
printing the internal protobuf contents with `.ShortDebugString()`.
Since this format exposes internal implementation details that we don't
want external users or computers to depend on, I changed op<< ->
PrintTo() to make it clearer that this "formatting" is only inteded for
nice output during failed gtest assertions.
Changed the IsType() functions that used to return bool to instead
return the type code so that it can …
> Refactoring to make it easier to add spanner ARRAY support.

- bazel/google_cloud_cpp_spanner_deps.bzl
- google/cloud/spanner/BUILD
- google/cloud/spanner/spanner_tool.cc
We only had a dep on GCS because of a time formatting library, that was
moved out of GCS into google/cloud/internal/.
modified:   bazel/google_cloud_cpp_spanner_deps.bzl
modified:   google/cloud/spanner/BUILD
modified:   google/cloud/spanner/spanner_tool.cc
Fixes #44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/56)
> Removed dep on GCS.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
A Spanner ARRAY is represented as a std::vector<T>, where T is any other
valid Spanenr type. Well, technically, arrays of arrays are not allowed,
but we don't currently forbid this. We could/should add an enabler to
this constructor to prevent this.
This PR also changes `op==` to do comparisons by looking at the data member protobuf contents instead of converting to C++ types and using their `op==`. This change makes it easier to recursively call the equality function for containers that can contain other values and containers.
Closes #53 
modified:   value.cc
modified:   value_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/ …
> Adds support for spanner ARRAYs.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
We choose to treat `spanner::Value` as `T(null, v1, v2, ...)`
rather than `null + T(v1, v2, ...)` or something between the
two.  That is, the null value is typed.  `v.is_null<T>()` is false if
`!v.is<T>()`, even when v is null, but the typical decision tree
would always test `v.is<T>()` first.
Fixes #49 .
> Make spanner::Value::is_null() a template

- google/cloud/spanner/CMakeLists.txt
I forgot to clean this up, we no longer need the `storage_client` to
compile the code.
> Do not use storage_client in CMake.

- ci/kokoro/Dockerfile.ubuntu
- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/cmake-super-presubmit.cfg
- ci/kokoro/docker/cmake-super.cfg
- ci/super/CMakeLists.txt
- cmake/external/c-ares.cmake
- cmake/external/crc32c.cmake
- cmake/external/curl.cmake
- cmake/external/external-project-helpers.cmake
- cmake/external/google-cloud-cpp.cmake
- cmake/external/googletest.cmake
- cmake/external/grpc.cmake
- cmake/external/protobuf.cmake
- cmake/external/ssl.cmake
- cmake/external/zlib.cmake
- doc/setup-cmake-environment.md
Create configuration files to verify our CMake files can be used as part
of a super-build.  These should probably live in google-cloud-cpp, but we
need to do a lot of refactoring there to allow this.
As a side benefit, we get a relatively easy way to install all the
dependencies in $HOME/local (or a similar directory). This is more
flexible than `vcpkg`, and less cumbersome than installing in
`/usr/local/`.
Add CI build configuration to automatically test this, though an additional
internal CL will be needed to enable this. 
Fixes #40 and fixes #42.
> Create file to support super-builds and test them.

- .clang-tidy
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- cmake/EnableClangTidy.cmake
- cmake/EnableWerror.cmake
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Enable clang-tidy (with warnings-as-errors), -Wall, -Wextra, and
-Werror. This commit will not fix any issues in the code, I want a build
that captures all the errors.
Fixes #62 and fixes #25.
> Enable clang-tidy and -Werror.

- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- cmake/EnableDoxygen.cmake
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/value.h
This enables support for Doxygen in CMake. Assuming you have Doxygen
installed: `cmake --build cmake-out --target doxygen-docs` will generate
the Doxygen documentation (as HTML). I enabled this in one of the CI
builds because this checks that the documentation "compiles", for
example, any cross-references must be valid.
Part of the work for #8.
> Add support for Doxygen and run it in a build.

- doc/setup-cmake-environment.md
Turns out vcpkg downloads and installs ninja (and CMake for that
matter). There is no need to tell folks to install it themselves.
> Simplify instructions for vcpkg.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
With this refactoring, the GetType() helper is now the only place that
maps C++ types to spanner type codes (e.g., std::int64_t ->
TypeCode::INT64). All the constructors now call GetType() to set the
type_ data member.
Now that "MakeNull" no longer needs to call a private constructor, a
MakeNullValue() factory is only a convenience function and does not need
any private or friend access to the value class. Therefore, it's nice to
make this a non-member function, which increases encapsulation since
fewer functions have access to Value's non-public members (this is a
pattern encouraged by many including Scott Meyers). Also,
spanner::MakeNullValue() is two fewer characters (removes an unneeded
"::").
modified:   value.cc
modified:   value_test.cc
--- …
> Cleanup: Prefer GetType() over type_.set_code; MakeNull is now a non-member

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
This refactoring makes all constructor bodies look the same: 1 statment
setting the type_ member using `MakeTypeProto()`, and 1 statement
setting the value_ member using `MakeValueProto()`. This way we can
re-use the make-a-value-proto logic without having to invoke the
constructor then steal the value_ data member from it.
This refactoring was done in preparation for adding Spanner Struct
support, which I suspect will involve some form of std::typle, which
should work well with helper functions like this.
modified:   value.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/77)
> Refactored c'tor bodies to MakeValueProto() function.

- .bazelrc
- ci/kokoro/Dockerfile.fedora-libcxx-msan
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/msan-presubmit.cfg
- ci/kokoro/docker/msan.cfg
The MemorySanitizer will help us detect unitialized reads. This is the
one sanitizer that must be turned on for all the code, including the C++
library (presumably the C library too, but the C++ library seems to be
enough). In this PR we introduce support for the MemorySanitizer,
enabling the build would require a internal CL in Google.
This fixes #41. Incidentally, we get a CI build using libc++ on Linux too.
> Support builds with the MemorySanitizer.

- ci/kokoro/Dockerfile.centos
- ci/kokoro/docker/build.sh
- google/cloud/spanner/value_test.cc
Create configuration files to build with gcc-4.8, the oldest compiler we are planning to support. A separate internal CL will enable this build.
> Support building with gcc-4.8.

- ci/check-style.sh
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/docker/build-in-docker-cmake.sh
Install the ShellCheck package needed for check-style.sh.  Also move
the "chmod" in replace_original_if_changed to a more logical location.
Emit the "Running the unit tests" message in build-in-docker-cmake.sh
before actually running the tests.
> Add the package for "shellcheck"

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Fixes #54 
Adds support for Spanner STRUCT. This is represented in C++ as `std::tuple<Ts...>`, where each `T` is any valid Spanner type, including another `std::tuple`. Each field may optionally contain a name, which is specified as a tuple element of type `std::pair<std::string, T>`.
@devbww this is a larger PR than I wanted. Feel free to ping me on chat or otherwise if you'd like to ask about or discuss parts of this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/88)
> Adds Spanner STRUCT support to Value

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
1. Standardized on STRUCT when specifically referring to the Spanner
type. Use struct when referring to a generic struct or C++ struct.
2. Fixed tyop.
3. Factored out function for `EqualTypeProtosIgnoringNames`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/94)
> Some cleanup from post-merge comments from PR #88

- google/cloud/spanner/value.h
Fixes #59
This PR adds an `is_vector` metafunction and `static_assert`s in the
constructor's body to disallow vector of vector. I choose to use a
static_assert in the body here instead of an enabler in the template
parameter list for several reasons:
1. Using `std::enable_if` in the template parameter list requires that
the metafunction be defined first, so it would have to live above the
constructors in the Value class, instead of being "hidden" at the bottom
of the class in the private section.
2. The static_assert() produces a slightly clearer error message in this
case.
3. Enablers are most useful when the goal is to disable an overload so
that *some other overload* can be used instead. That's not the goal
here. In this case, we're just detecting an error case. There's no
alterative …
> Static assert that vector of vector is not allowed.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Since integer literals are of type int and string literals are of type
char const* (actually arrays, but they decay to pointers), it would be
nice to allow constructing a Value directly from these commonly used
literal types. These types don't directly map to supported Spanner
types, so we'll up convert both of them to std::int64_t and std::string
respectively.
Fixes #93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/95)
> Allows Value construct from int and string literals.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
All public constructors now call one private templated constructor that
sets the type_ and value_ members.
@coryan you previously referred to a simpler constructor /implementation/. I'm not sure if this is what you were referring to (maybe?), but I think I like this better than the repeated c'tor bodies that this code previously had.
Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/96)
> Simplifies the Value constructor implementations.

- cmake/EnableClangTidy.cmake
This removes the options from the CMake UIs, and makes it easier for our
users to discover the interesting tweaks.
> cleanup: Mark uncommon CMake options as "advanced".

- ci/kokoro/docker/build.sh
This is the oldest version we support on `google-cloud-cpp`.
Fixes #73.
> Support Clang-3.8 build.

- google/cloud/spanner/value.h
When `google::cloud::spanner` grows an internal namespace, this
reference to `internal::ThrowInvalidArgument()` will start meaning
something else.  So spell out that `google::cloud::internal` is
the namespace we are really looking for.
> fix: Fully qualify the namespace for ThrowInvalidArgument()

- .clang-format
- google/cloud/spanner/spanner_version_test.cc
- google/cloud/spanner/value.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/117)
> cleanup: Make clang-format put the spanner headers first.

- bazel/googleapis.BUILD
- google/cloud/spanner/BUILD
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/client_options.cc
- google/cloud/spanner/client_options.h
- google/cloud/spanner/client_options_test.cc
- google/cloud/spanner/internal/database_admin_stub.cc
- google/cloud/spanner/internal/database_admin_stub.h
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/spanner_tool.cc
This PR introduces a Stub class for spanner::DatabaseAdmin. It
implements functions to create and drop a database. This will be useful
as we write integration tests, because we should run those tests in
dynamically created databases, isolated from each other, to avoid
flakiness due multiple tests operating on the same data.
A future PR will introduce a simple Client class, I think this is enough
to get us going though.
> Implement basic Stub for DatabaseAdmin.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/spanner_tool.cc
The `spanner_tool` program was not getting clang-tidy nor code coverage
options.
> bug: Add options to spanner tool

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Adds support for getting the raw protos from a `spanner::Value` and constructing a `spanner::Value` from raw protos. This is needed for converting the raw request/response protos to/from `spanner::Value` objects.
Note: In a later PR, we'll add support for checking for invalid protos. See #122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/131)
> Added ToProto/FromProto support for Value

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
When constructing a `Row` from a T that is the same as `Row<Ts...>`,
that should be handled by the copy constructor, not the
perfect-forwarding constructor. To do this, we need to disable the
perfect-forwarding c'tor if any of its given `Ts` is Row.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/136)
> Disables forwarding c'tor if T == Row.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
`Value::GetValue(optional<T>, ...)` must check the `google::protobuf::Value`
for nullness if it is ever going to produce an `optional<T>{}`.
Change `Value.BasicSemantics` to correctly produce `vector<optional<T>>`
values that have some elements present and some missing.
Don't forward the `Value` private ctor argument to `MakeTypeProto()`.
`MakeTypeProto()` is responsible for taking its argument by value or
`const&`, and the ctor argument is only forwarded to `MakeValueProto()`.
Also use a non-throwing string->integer conversion function in
`Value::GetValue(std::int64_t, ...)`. This will help with #122.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/137 …
> fix: Value::GetValue(optional<T>, ...) must check for nullness

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/database_admin_client.h
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/spanner_client_unit_tests.bzl
This PR implements initial unit tests for DatabaseAdminClient. The unit
tests can verify the code works in conditions that are hard to produce
in an integration tests, such as specific failures or timeouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/135)
> feat: Implement unit tests for DatabaseAdminClient.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/date.h
- google/cloud/spanner/date_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
Standard C++11 lacks a good "date" abstraction, so we supply a simple
implementation of a YMD triple. There is no range checking or field
normalization, and no operations.  Just enough to use it as a Value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/143)
> Introduce google::cloud::spanner::Date to represent a Spanner DATE

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
TIMESTAMP is represented by `std::chrono::system_clock::time_point`
(although see #138), and DATE by a new, simple "YMD" type,
`google::cloud::spanner::Date`.
Fixes #50 and #51.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/149)
> feat: Implement spanner::Value support for TIMESTAMP and DATE

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/tuple_utils.h
- google/cloud/spanner/internal/tuple_utils_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/value.h
Refactors the `IterateTuple` function from the private section of `Value` into `internal/tuple_utils.h` so that it can be used from other places (I'll need this from an upcoming "RowParser" class). The function is renamed to `internal::ForEach`.
This PR also makes the implementation a bit more generic so that it will work with not just `std::tuple`, but also any class that looks like a tuple, that is any class template that takes a variable number of template parameters. This will make `ForEach` work with the `Row<Ts...>` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/146)
> Iterate tuple

- google/cloud/spanner/internal/time_format.cc
- google/cloud/spanner/internal/time_format.h
Also use `std::size_t` instead of `std::string::size_type`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/150)
> Document the return value of ParseTime()

- google/cloud/spanner/internal/tuple_utils.h
- google/cloud/spanner/internal/tuple_utils_test.cc
For a type to work with `internal::ForEach`, that type must now provide
a non-member function named `GetElement<I>(T)` that can be found via
ADL. It should do the equivalent of what `std::get<I>(T)` does, but this
differently named function makes it so we don't need to step on
`std::get`'s toes. It also avoids our need to implement a
namespace-scope function named "get", which violates a
clang-tidy-enforced readability rule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/151)
> Removes need for tuple-like types to overload ADL `get<I>(T)`.

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
In order to be able to detect invalid protobufs, `Value::GetValue` needs to return `StatusOr<T>`. This PR adds that support, and some tests to verify its behavior. This is needed for the upcoming RowParser (#32)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/152)
> Makes Value::GetValue() return StatusOr<T>

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
Adds a `ParseRow()` function to row.h that knows how to extract C++ types form a `std::array` of `spanner::Value` objects. This function will be called from an upcoming "RowParser" class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/153)
> Adds ParseRow() function

- .clang-tidy
- google/cloud/spanner/version.cc
I would like us to share these files, but that sounds hard, we should
keep them consistent in any case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/154)
> cleanup: Make .clang-tidy consistent.

- google/cloud/spanner/value_test.cc
None of the tests for `Value` set or extracted a non-null optional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/155)
> cleanup: Test extracting non-null optionals.

- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
A default-constructed Value represents no value with no type. This is
needed in order to create a `std::array` of Value objects.
modified:   value_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/156)
> feat: Add a default c'tor for Value

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
This is useful when callers need to know how many columns the row
contains but they don't have an instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/159)
> feat: Made Row::size() member static.

- bazel/google_cloud_cpp_spanner_deps.bzl
- bazel/googleapis.BUILD
- ci/kokoro/Dockerfile.fedora-install
- cmake/external/google-cloud-cpp.cmake
- google/cloud/spanner/BUILD
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/database_admin_client.cc
- google/cloud/spanner/integration_tests/BUILD
- google/cloud/spanner/internal/database_admin_stub.cc
- google/cloud/spanner/internal/spanner_stub.cc
Fixes #129 
This updates the `google-cloud-cpp` dep and changes any appropriate references to `grpc_utils`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/165)
> Remove dependency on bigtable_client.

- .cmake-format.py
- ci/super/CMakeLists.txt
The integration tests require a custom config. This shows that we have
not enabled the super build, I will fix that in a separate CR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/167)
> bug: Do not run integration tests in super-build.

- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/kokoro/Dockerfile.fedora-install
- cmake/external/google-cloud-cpp.cmake
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/internal/retry_loop_test.cc
This updates google-cloud-cpp to pull in the `testing_util` changes and changes the test to use `EXPECT_STATUS_OK`. Note that I moved building google-cloud-cpp after googletest because I originally got an error; it should be faster this way too since googletest will probably not change as often as google-cloud-cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/168)
> Use EXPECT_STATUS_OK in integration test

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/time.cc
- google/cloud/spanner/internal/time.h
- google/cloud/spanner/internal/time_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/timestamp.h
- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Previously we chose `std::chrono::system_clock::time_point` to represent
a spanner TIMESTAMP, but it has a platform-specific resolution. Now
we use `time_point<system_clock, nanoseconds>` to explicitly match the
resolution required by Spanner. This allows a timestamp generated on one
machine to be reconstituted intact on another machine.
Revert to testing with nanoseconds. Previously we used microseconds as
that was the common resolution of `system_clock::time_point` over all
supported platforms.
Fixes #138.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/169)
> feat: Use a fixed type for TIMESTAMP

- google/cloud/spanner/row_parser.h
- google/cloud/spanner/row_parser_test.cc
`RowParser<Ts...>` no longer accepts an input range of `Value` objects. Instead, it now consumes `Values`s from a caller-provided functor. This functor will allow the `Client` class to inject code to read protos and values from a gRPC stream.
Other smaller changes in this PR:
*  RowParser now requires at least 1 template parameter. It made not sense to have a row parser that was parsing nothing for each row.
* Any failure during iteration will halt further iteration by advancing the iterator to end.
* The caller-provided `ValueSource` functor may return a `StatusOr` to indicate a failure producing the `Value` object. (@coryan 's prediction yesterday was correct :-) )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix: RowParser consumes Values from functor, not input range

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/database_admin_client.cc
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/internal/database_admin_retry.cc
- google/cloud/spanner/internal/database_admin_retry.h
- google/cloud/spanner/internal/database_admin_stub.cc
- google/cloud/spanner/internal/database_admin_stub.h
- google/cloud/spanner/internal/polling_loop.h
- google/cloud/spanner/internal/polling_loop_test.cc
- google/cloud/spanner/polling_policy.h
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
This PR introduces a `spanner::PollingPolicy` to control for how long we
poll longrunning operations. We use this policy in the
`internal::DatabaseAdminRetry` decorator, and refactored the polling
loop to a function, so we can test it.
I removed a number of tests for DatabaseAdminClient because they
basically repeat the (more generic) tests for `internal::PollingLoop`.
Fixes #128 and fixes #126.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/174)
> feat: Use policies to control polling.

- google/cloud/spanner/internal/database_admin_retry.cc
- google/cloud/spanner/internal/polling_loop.h
- google/cloud/spanner/internal/polling_loop_test.cc
Some operations (like the upcoming `UpdateMetadata()`) use long-running
operations, but all the interesting results are in the metadata field,
not the response field. This change refactors the code to support
extracting the result from either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/201)
> cleanup: Support metadata as result in PollingLoop.

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
This accessor lets callers extract all the columns from a row without
explicitly knowing the corresponding C++ types by getting a std::array
of Value objects. Those could then be interogated to figure out their
values, or the raw protos could be extracted.
I suspect this might be useful for the upcoming KeySet implementation: #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/214)
> feat: Adds Row::values() accessor that returns std::array<Value, N>

- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/install-bazel.sh
Fixes #104 
This also updates gRPC. At some point, Bazel flipped the default value of `incompatible_depset_is_not_iterable` from `false` to `true`, requiring the `to_list()` method to be used. Those changes are available in a newer version of gRPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/220)
> Update Bazel to 0.28.0

- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
I kind of forgot that mutations apply to an specific table :disappointed: 
Part of the work for #198.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/230)
> feat: Require a table name in mutation builders.

- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
This proposes two separate functions to add the values vs. add a row object into the mutations.
Part of the work for #198. Fixes #222.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/231)
> feat: Separate AddRow vs. EmplaceRow.

- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/233)
> bug: Always require column names for mutations.

- google/cloud/spanner/mutations.h
(I think) EmplaceRow exists as a convenience for users who have values
but no row yet. Logically users are adding a row, but since they only
have values, we'll construct the Row for them. Therefore, it may make
sense to have EmplaceRow() be a simple 1-line forwarder to AddRow(), to
have a implementation for both functions.
This also simplifies the implementation a little since `Row` already handles all the variadic stuff.
Modulo an extra move here or there, I don't think this will result in
any extra/unnecessary copies, so I think performance wise this would be
pretty close to a wash. But someone with a better eye than me may be
able to point out if/where my assumptions are wrong.
I'm not wedded to this. It's just something for us to consider.
--- …
> Make EmplaceRow forward to AddRow

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
A `Row<Ts...>` represents a list of column values. Typically, each value
is a supported C++ type (bool, std::int64_t, std::string, etc). But
there may be cases where it's convenient to create a "row" of
`spanner::Value` objects, such as if/when one already has a `Value`
objec that they'd like to add to the Row, or maybe if one is reading the
results of a query and may doesn't know the type of the value (yet) and
would like to handle it in some type-erased way.
Related to #231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/232)
> feat: Add support for Row<Value>

- google/cloud/spanner/database_admin_client.h
Mismatched quote vs. backtick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/234)
> doc: Fix Doxygen formatting.

- google/cloud/spanner/row_parser.h
- google/cloud/spanner/row_parser_test.cc
`RowParser<Ts...>` now accepts the ValueSource functor wrapped in a shared_ptr. This allows the ResultSet to construct a single shared ValueSource that it shares with RowParser. 
A few fallouts from this change:
1. RowParser and ResultSet will now have independent lifetimes.
2. If a RowParser is moved to another RowParser, the second one will continue where the first left off. 
Related to #221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/226)
> fix: RowParser accepts shared_ptr<ValueSource>

- google/cloud/spanner/row_parser.h
- google/cloud/spanner/row_parser_test.cc
This PR makes several changes to `RowParser` to simplify its implementation (a bit) and to give it more natural semantics in the face of copies and moves. The changes are as follows.
1. The "advancing" logic was pulled out of `iterator::operator++` and moved into `RowParser::Advance` (private). This allows the single stored `curr_` row (the one returned when dereferencing the iterator) to be stored in the RowParser class rather than in the iterator itself. This means that the act of *moving* a `RowParser` does not also consume the next Row from the stream. This is the reason for the change in `row_parser_test.cc`, and if you look at the behavior before and after this change, I think you'll agree that the new behavior is preferable.
2. Fewer copies of the `value_source_` std::function. Now …
> fix: RowParser improvements

- bazel/googleapis.BUILD
- ci/check-style.sh
- ci/test-install/WORKSPACE
We were missing WORKSPACE files and a couple other files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/241)
> cleanup: Enforce formatting on all Bazel files.

- google/cloud/spanner/value.h
I didn't completely follow the suggestion in #157, so if these changes don't clarify the point about an empy `Value`, let me know and I'll fix them.
Fixes #157
[skip ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/242)
> Clarified docs about a default constructed Value.

- google/cloud/spanner/doc/spanner-main.dox
This creates a landing page for the reference docs and describes how to
use the library from CMake, Bazel, and Make.
Part of the work for #195.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/247)
> feat: Create landing page for reference docs.

- google/cloud/spanner/row_parser.h
- google/cloud/spanner/row_parser_test.cc
These changes make it so RowParser never consumes a value on construction nor move nor copy. Only its iterators consume a value and only when they must: on first construction, and `op++`. I believe this provides the safest and least surprising semantics. For example:
```cc
auto rp1 = result_set.Rows<A, B, C>();
auto rp2 = result_set.Rows<A, B, C>();  // OK: no values consumed
auto rp3 = rp2;  // OK; no values consumed.
auto it = rp3.begin();  // 1st value consumed
assert(it == rp3.begin());  // No additional values consumed
assert(it != rp3.end());  // No values consumed
auto x = *it;  // No values consumed
assert(x == *it);
++it;  // 2nd value consumed
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix: RowParser now behaves better and only consumes a Value when it must

- cmake/external/curl.cmake
Fixes https://github.com/googleapis/google-cloud-cpp-spanner/issues/249
This took me way longer to notice than I would like to admit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/250)
> bug: Add CMAKE_PREFIX_PATH to external/curl.cmake

- .gitignore
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
This file will be generated by our "cmake" build. This file is needed
for users who want to use clangd. Clangd will not automatically find
this file burried in the build directory. So for users who want to use
this file, they can set a top-level symlink pointing to
cmake-out/spanci-fedora-install-30-cmake/compile_commands.json.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/253)
> Add support to generate compile_commands.json file

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/base64.cc
- google/cloud/spanner/internal/base64.h
- google/cloud/spanner/internal/base64_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
Encoding and decoding of base64 strings to support the `BYTES` type.
Fixes #123.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/255)
> feat: Add `internal::Base64Encode()` and `internal::Base64Decode()`

- .gitignore
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
This reverts commit 6131abb4618d00ce88a97804380602d0ff2a816e.
I'm reverting this because the `compile_commands.json` file produced by cmake in the docker image doesn't contain the needed paths to the deps because in the docker image most deps are found in standard places like /usr/local, etc, so the needed `-I ...` flags are not included in the compile commands.
We should be able to get bazel to generate a more complete compile_commands.json file for us since it sees all of our deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/256)
> Revert "Add support to generate compile_commands.json file (#253)"

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
The fixes don't actually change any behavior, and the previous code was
also correct. However, clang 3.8 incorrectly warned about some valid
constructs. But since we have a CI build for clang 3.8, it would be good
to not produce the warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/260)
> Fix some compile warnings with clang 3.8

- ci/kokoro/docker/build-in-docker-cmake.sh
We want the `CMAKE_FLAGS` variable to expand as separate arguments, so
we disable the shellcheck warning on that line. This is copying the [same
technique done in google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp/blob/master/ci/kokoro/docker/build-in-docker-cmake.sh#L76).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/259)
> Silence shellcheck warning.

- google/cloud/spanner/internal/base64.cc
The fixes don't actually change any behavior, and the previous code was
also correct. However, clang 3.8 incorrectly warned about some valid
constructs. But since we have a CI build for clang 3.8, it would be good
to not produce the warnings.
See also #260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/261)
> fix: some compile warnings with clang 3.8

- google/cloud/spanner/sql_partition.cc
- google/cloud/spanner/sql_partition.h
- google/cloud/spanner/sql_partition_test.cc
Since @tmatsuo added equality to `SqlStatement` in #216, we can now make
`SqlPartition` a regular type with equality support. Also adds unit test
for this functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/252)
> feat: give SqlPartition equality support

- google/cloud/spanner/client.h
With overloads, use `@copydoc` to copy the documentation and just
document any additional parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/291)
> cleanup: Fix a few doxygen nits.

- google/cloud/spanner/transaction.h
- google/cloud/spanner/transaction_test.cc
Fixes #296.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/300)
> Implement `MakeReadOnlyTransaction()` and `MakeReadWriteTransaction()`

- google/cloud/spanner/internal/date.cc
- google/cloud/spanner/internal/date_test.cc
The new implementation avoids internal/time_format.h, which is slated
for removal, the end goal being to produce `TimestampToString()` and
`TimestampFromString()` functions that can be shared between bigtable,
storage, and spanner libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/299)
> Reimplement `DateToString()` and `DateFromString()`

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/BUILD
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/random_database_name.cc
- google/cloud/spanner/testing/random_database_name.h
I am going to create a new integration test, and want to use this
function in it. Refactor the function to the testing library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/292)
> cleanup: Refactor RandomDatabaseName() function.

- .gitignore
I missed the configuration file because it was captured by one of
the .gitignore globs. Add the configuration file and fixed .gitignore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/304)
> bug: Fix Bazel presubmit configuration.

- ci/kokoro/macos/build-cmake.sh
- ci/kokoro/macos/build.sh
Fix the driver scripts for macOS+CMake, I needed the changes to
the spanner_testing library before testing said scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/303)
> bug: Fix macOS+CMake build.

- ci/kokoro/macos/build-cmake.sh
On Kokoro the dependencies (libressl in our case) need to be manually
installed before running the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/309)
> bug: Install dependencies on Kokoro.

- google/cloud/spanner/client.cc
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/transaction.h
- google/cloud/spanner/transaction_test.cc
The function was using a `std::function<T(...)>` and made it hard to use
with lambdas. Since it was already a template (and its implementation
too), I decided to use the functor type all the way through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/313)
> feat: Generalize internal::Visit(Transaction).

- google/cloud/spanner/row_test.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Fixes #312
Removed `Value::is<T>()`, because it only verified the type of the
contained value, not whether it the contained value is "valid". Also removed
`Value::is_null<T>()` because it duplicated work done by `get<T>` (see #49). These two
methods mislead users into thinking that they were actually validating the `Value`
object in some meaningful way. The truth is that the only
way to verify complete validity is to attempt to fully parse the
contained value and see if it succeeds. This is what `Value::get<T>()`
does.
I can't think of any use-case where a caller would want `is<T>()` or `is_null<T>()`
without also needing `get<T>()`, and we have several cases users were
confused by the current API.
Additionally, this PR removes the `operator T()` conversion operator.
This is because …
> fix: Removed redundant/confusing parts of Value API

- google/cloud/spanner/internal/compiler_info.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/318)
> fix: Use 4-digit year for consistency

- google/cloud/spanner/value_test.cc
MSVC uses 32-bits for "long":
https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/325)
> fix: Use long long literals for MSVC compiler.

- .clang-tidy
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/internal/build_info.cc.in
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
- google/cloud/spanner/internal/retry_loop_test.cc
- google/cloud/spanner/internal/spanner_stub.cc
- google/cloud/spanner/result_set_test.cc
- google/cloud/spanner/spanner_version_test.cc
- google/cloud/spanner/sql_partition_test.cc
- google/cloud/spanner/testing/matchers.h
- google/cloud/spanner/value.cc
- google/cloud/spanner/version.cc
- google/cloud/spanner/version.h
Enabled a few more clang-tidy checks, and removed some checks that were
unnecessarily noisy and causing us to need `NOLINT`. Removed or worked
around all of our existing `NOLINT` declarations.
Fixes #316 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/333)
> Cleaned up .clang-tidy file.

- ci/check-style.sh
- ci/kokoro/docker/build.sh
This change passes an env var to the docker builds to let them know if
they are running as part of a CI or a human invocation. In the former
case, there is no change. In the latter case, some scripts may want to
be a little more friendly. For example, in this PR, I changed the
clang-tidy build to not bail if there are existing uncommitted files.
Instead, the the clang-tidy build will simply format the local files and
leave them edited in the working dir. The author can then look at the
diffs and commit them. This makes "build.sh clang-tidy" a more useful
tool for developers who want to use it to format their existing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google- …
> feat: let clang-tidy build not fail if there are edited files.

- google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/332)
> Quash a clang-3.8 warning (suggest braces around initialization)

- google/cloud/spanner/date.h
- google/cloud/spanner/date_test.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Add all relational operators to `Date` and `Value::Bytes`, so
that the ordering of each Spanner types is now reflected in the
ordering of its C++ mapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/319)
> Make the C++ mappings of orderable Spanner types also orderable

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/internal/transaction_impl_test.cc
- google/cloud/spanner/transaction_test.cc
Pass a monotonically-increasing sequence number to each transaction
visitor.  This will provide a way to sequence read-write `ExecuteSql()`
calls.  See ExecuteSqlRequest.seqno for more details.
Fixes #279.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/331)
> Provide an ordering to transaction visitors

- google/cloud/spanner/internal/transaction_impl.h
Use `static_assert()` when you want to produce a compilation error,
and `std::enable_if<>` when you want to eliminate an overload.
This is an instance of the former.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/337)
> Prefer static_assert() over std::enable_if<>

- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
- google/cloud/spanner/internal/retry_loop_test.cc
These are no longer applicable since #333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/341)
> Delete "makes clang-tidy angry" comments.

- google/cloud/spanner/client_test.cc
- google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
- google/cloud/spanner/internal/build_info_test.cc
- google/cloud/spanner/internal/compiler_info_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/retry_loop_test.cc
IDK if everyone agrees with this, but it's what I'm used to and it makes the tests easier to read IMO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/343)
> Always use using-declarations for symbols in ::testing

- .clang-format
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
- google/cloud/spanner/keys_test.cc
- google/cloud/spanner/mutations_test.cc
- google/cloud/spanner/sql_statement_test.cc
I also changed the quoting of the existing proto strings, and expanded the repeated fields and maps to use repeated field names rather than the bracket syntax, which clang-format does not seem to handle well. Then I let clang-format reformat them all.
`EnclosingFunctions` is supposed to make this "automatic" based on the function name, i.e. you can just write `R"(` rather than `R"proto(` when calling one of those functions. I decided not to use it since it appears to only look at the function name itself and I thought `ParseFromString` was overly broad. I tried to set it to `TextFormat::ParseFromString` (and the fully qualified name) but those didn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Enable clang-format proto raw string formatting.

- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
`DeleteMutationBuilder` isn't so much a builder as all the "add"
parts are actually delegated to `KeySetBuilder`, but it is probably
best to maintain a consistent vocabulary between it and the other
`Mutation` builders.
This also means there is no need for anything beyond the "simple"
test case.
Fixes #277.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/348)
> feat: Implement spanner::MakeDeleteMutation()

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_options.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/keys.h
I'm still planning to add more tests, but this has basic unit tests for `Read` and `ExecuteSql` and I believe the implementation of both is complete. I think it would also be valuable to get some samples and integration tests written, which is blocked by checking this in.
Fixes #283 
Fixes #285 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/350)
> feat: add Read and ExecuteSql methods

- google/cloud/spanner/client.h
- google/cloud/spanner/connection.h
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
These were discussed while reviewing other PRs and/or in chat:
- Remove comments from `connection.h` in favor of `client.h` and merge the two versions of the `Rollback` comment into one.
- Add a comment about RW vs RO transactions to `Commit`.
- Remove some unnecessary namespace qualifiers.
- Change `ConnectionImpl::Commit` to take `CommitParams` for consistency.
- Add parameter names in `ConnectionImpl` methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/352)
> Misc small cleanups in client/connection:

- google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/partial_result_set_reader.cc
- google/cloud/spanner/internal/partial_result_set_reader.h
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
In gRPC the `grpc::ClientContext` used for a streaming RPC must
have a lifetime at least as long as the RPC does.  The client context
is used to store any metadata headers (potentially) returned by the
server, and those are not updated until the `Finish()` call.
Because `grpc::ClientContext` disallows copying and moves, we need
to wrap it in a `std::unique_ptr`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/353)
> bug: Fix crashes in Client::Read and Client::ExecuteSql.

- google/cloud/spanner/keys.cc
- google/cloud/spanner/keys.h
A few small cleanups to `keys.h`
* Renamed enum from MACRO_STYLE to kConstant style, per the style guide.
* Use some existing factory functions and removed the need for some friendships.
* Tweak to `KeySetBuilder` docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/354)
> chore: Small style cleanup to keys.h

- google/cloud/spanner/keys.cc
- google/cloud/spanner/keys.h
- google/cloud/spanner/keys_test.cc
We don't need to implement our own type-erased key and range types if we
directly use the `KeySet` proto, which itself is type erased. This also
eliminates a copy/move since we ultimately need the data in proto form
anyway.
Also note that this PR removes `KeySet::IsAll()`. We could add that back, but I removed it because it's not longer needed, and we don't have any other accessors on `KeySet`, so exposing the accessor for `IsAll()` seemed odd.
I'll have an upcoming PR after this one that makes better use of "moves" so we don't copy the Values around as much. But I was trying to break up the changes into small chunks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud …
> chore: Use KeySet proto as type-erased storage

- google/cloud/spanner/keys.h
- google/cloud/spanner/keys_test.cc
As discussed offline, it seems unclear what a default constructed `Bound` means. Using a default constructed `Row` is still some valid instance, and it's not clear whether it's a good default. At this point, I don't think we need default construction, so it seems safe to remove it for now because we can always add it back later if we need to.
I also renamed `MakeKeyRange` -> `MakeKeyRangeClosed` to make it explicit that the range would be closed. This is now the only place where "closed" is a default value, and it'll be explicit at the call site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/364)
> feat: Remove default construction from Bound and KeyRange

- google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
- google/cloud/spanner/internal/partial_result_set_reader.cc
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
Spanner returns no row types for DELETE and (I think) INSERT queries.
Fixes #360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/363)
> bug: PartialResultSet can have no row types.

- google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
- google/cloud/spanner/row.h
Wrote an integration test for Client::Rollback(). To do so, I also wrote
a test that performed multiple SQL statements in a single transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/366)
> feat: Integration tests for Rollback().

- google/cloud/spanner/keys_test.cc
This is actually a small PR, but it looks bigger than it is because I re-arranted some TEST functions so they match the order they're declared in in the `.h` file.
The only actual change in this PR is the addition of the `TEST(KeySetTest, RoundTripProtos)` function to unit test `internal::FromProto`
Related to #365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/371)
> feat: added unit test for FromProto

- google/cloud/spanner/keys.h
- google/cloud/spanner/keys_test.cc
Rvalue-ref qualifies the `KeySetBuilder<T>::Build()` method which will enable it to *move* all of its data into the protos in the resulting `KeySet`. I needed to add rvalue-qualified accessors to Bound and KeyRange as well.
I left the `KeySetBuilder<T>::Build() const&` overload, which is inefficient and will result in a copy of all the keys. We could remove this overload if we want to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/373)
> feat: makes KeySetBuilder<T>::Build() more efficient with rvalue qualifier

- google/cloud/spanner/internal/partial_result_set_reader.cc
- google/cloud/spanner/internal/partial_result_set_reader_test.cc
I don't know if this is likely to happen in practice but I don't think
this is necessarily an error so we should be permissive.
Once place where I might envision it actually happening is at the end
of the stream -  maybe we could get a response with stats but no values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/375)
> Handle a response with no values.

- google/cloud/spanner/internal/partial_result_set_reader.cc
Small thing (leading to extra copying) that I missed when implementing this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/380)
> Make NextValue() std::move from the received value.

- .clang-tidy
- ci/test-install/spanner_install_test.cc
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/database.cc
- google/cloud/spanner/database.h
- google/cloud/spanner/database_admin_client.cc
- google/cloud/spanner/database_admin_client.h
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/database_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
Fixes #369 
This PR adds the `Database` class, which identifies a Spanner database. It is constructed with a `project_id`, `instance_id`, and `database_id`.
All functions that need these fields now accept a `Database` argument instead of a `std::string` or 3-separate `std::string`s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/382)
> feat: Add `Database` class to encapsulate project_id, instance_id, database_id

- google/cloud/spanner/samples/samples.cc
This fixes #180 and fixes #181.
I also implemented the `spanner_update_data` sample, there was no
issue for it, but we need to prepare the database state for these samples.
I refactored some of the support code because it was getting tedious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/391)
> feat: implement spanner_read_{only,write}_transaction samples.

- google/cloud/spanner/samples/samples.cc
This fixes #184, and makes all the `spanner_{update,delete,insert}_data` examples consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/401)
> cleanup: Simplify spanner_update_data sample.

- README.md
- ci/generate-badges.sh
Update the link to the reference documentation, so it is easier to
discover. Also updated the build badges, and created a script to
semi-automate the generation of the badges in the future.
This fixes (in my opinion) #193 .
If you are interested in the rendered version of this page, look in the source branch:
https://github.com/coryan/google-cloud-cpp-spanner/tree/update-readme-badges#readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/404)
> doc: Update README file badges and links.

- google/cloud/spanner/samples/samples.cc
Add the `spanner_field_access_on_struct_parameters` and the
`spanner_field_access_on_nested_struct` samples.
Fixes #191 and fixes #192.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/411)
> feat: Implement more Cloud Spanner STRUCT samples.

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/mutations.h
- google/cloud/spanner/samples/samples.cc
DO NOT SUBMIT.  FOR DISCUSSION ONLY FOR NOW.
Replace `TransactionAction` with `StatusOr<Mutations>` as the return
type for the `Client::RunTransaction()` functor. This makes it easier
to write a functor (addressing #390), and makes it very clear what
`RunTransaction()` should return when the transaction will be rolled
back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/397)
> Simplify Client::RunTransaction() functor interface

- .bazelrc
Without debug symbols the error messages are really hard to grok.
Compile with -Og -g for all sanitizer builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/434)
> chore: sanitizer builds should have debug symbols.

- ci/kokoro/docker/build-in-docker-cmake.sh
- google/cloud/spanner/row_test.cc
The gcov .gcda files for library files are shared across tests, and
written when the test finishes. If the tests are executed in parallel
some of the data may become lost (or the file corrupted). The easiest
fix is to run the tests sequentially. We could use a clever value for
GCOV_PREFIX and then aggregate the results, but that can be a future
improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/437)
> chore: run coverage tests sequentially.

- google/cloud/spanner/internal/logging_spanner_stub.cc
This could also be called "@coryan does not know how ternary operators work."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/488)
> bug: fix logging for streams.

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
This change introduces two tests, both work similarly: (1) they run
multiple threads, each thread runs for N seconds, (2) the thread picks
an action, row key, and query size at random, (3) if the action is
"insert" the thread inserts (or updates) the row with the given key, (4)
if the action is "select" the thread reads (or selects) the randomly
selected query size rows starting at the randomly selected key.
The test counts the number of successes and failures and expects less
than 0.1% failures.
This stress test is executed as part of the CI build, but it only runs
each test for 30 seconds. We should run it manually (or nightly) with a
much higher setting, maybe "24 hours" or something similar.
This (I think, but let me know if you disagree) fixes #455
--- …
> feat: Implement a simple stress test.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/doc/spanner-main.dox
- google/cloud/spanner/doc/spanner-mocking.dox
- google/cloud/spanner/samples/CMakeLists.txt
- google/cloud/spanner/samples/mock_execute_sql.cc
- google/cloud/spanner/samples/spanner_client_samples.bzl
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/mock_spanner_connection.h
Add a new sample showing how to mock a `spanner::Client`, because this
is a fairly difficult example to understand this change also adds a new
page to explain the example step-by-step.
This fixes #196
If you are interested in the rendered output from the docs, I manually uploaded them to this location:
https://coryan.github.io/google-cloud-cpp-spanner/pr530/spanner-mocking.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/530)
> feat: implement a mocking example.

- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/connection_options_test.cc
- google/cloud/spanner/internal/spanner_stub.cc
Populate the user-agent string with information about the library
version. Also allow applications to add their own user-agent string
prefixes.
This is part of the work for #224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/535)
> feat: populate the user-agent string.

- .bazelci/presubmit.yml
Currently it will build and run unit tests on Ubuntu 18.04.
The configuration file is explained at:
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/527)
> Add a configration file for bazelci

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
This is a small cleanup with no behavioral change. The changes are:
1. The non-virtual methods that are called from Visit are now named like *FooImpl*, to distinguish them from the overridden virtual *Foo* function. I did this because it makes it easier to navigate between the two functions (via text search), and overloading virtual and non-virtual functions is weird on its own.
2. Removed the doxygen comments from the private functions because they seemed redundant and unnecessary.
3. Made the `override` declarations in the .h file consistent in whether they declare the parameter name or not. I chose to remove them, but I don't feel strongly about naming them all either. (If we do name them, I'd vote to name them all `params`.)
--- …
> cleanup: connection_impl function naming

- google/cloud/spanner/internal/database_admin_stub.cc
- google/cloud/spanner/internal/instance_admin_stub.cc
This fixes #224.  Unfortunately I do not know of any way to write a unit or integration test for this, the state of the `grpc::Channel` or a gRPC-generated `FooStub` are not accessible in any way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/538)
> feat: implement user-agent string for admin stubs.

- google/cloud/spanner/integration_tests/BUILD
The CI builds that run integration tests sometime fail with a timeout.
The default timeout is 300s, this changes that timeout to 900s. Some of
the tests take about 90s to run (average, observed max is about 120s),
so 10x seems like a safe margin.
This is part of the work for #329, I do not believe it fixes it, but probably
makes it so unlikely that we won't care anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/542)
> chore: mitigate flakiness in integration tests.

- google/cloud/spanner/testing/database_environment.h
- google/cloud/spanner/testing/mock_spanner_connection.h
- google/cloud/spanner/version.h
A few of the namespaces did not have documentation (or the documentation
was slightly off).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/570)
> doc: Document namespaces.

- ci/kokoro/windows/bazel/build.bat
To workaround grpc/grpc#16872 we must run the integration tests serially
on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/578)
> bug: on Windows run integration tests serially

- google/cloud/spanner/instance_admin_client.cc
- google/cloud/spanner/instance_admin_client.h
- google/cloud/spanner/instance_admin_client_test.cc
- google/cloud/spanner/instance_admin_connection.cc
- google/cloud/spanner/instance_admin_connection.h
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/internal/instance_admin_retry.cc
- google/cloud/spanner/internal/instance_admin_retry.h
- google/cloud/spanner/internal/instance_admin_stub.cc
- google/cloud/spanner/internal/instance_admin_stub.h
- google/cloud/spanner/mocks/mock_instance_admin_connection.h
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/testing/mock_instance_admin_stub.h
Implement a function to list existing instances. Include the usual unit
tests, an integration test and one example.
Fixes #517.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/580)
> feat: Implement InstanceAdminClient::ListInstances.

- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/connection_options_test.cc
- google/cloud/spanner/internal/spanner_stub.cc
I did not think the `ConnectionOptions::clog_enabled()` option really
well. When I documented the other options I realized that this was out
of place.  Removed for now.
I did update the documentation of the other options too.
Fixes #561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/579)
> cleanup: remove ill-thought option.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
- google/cloud/spanner/samples/BUILD
- google/cloud/spanner/samples/CMakeLists.txt
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/database_environment.cc
- google/cloud/spanner/testing/pick_random_instance.cc
- google/cloud/spanner/testing/pick_random_instance.h
The CI builds run in parallel, and we have about 10 builds that run the
integration tests. Inside each build the integration tests themselves
run in parallel, and about 4 of them create new databases. That is about
40 databases created more or less simultaneously. Meanwhile, the maximum
number of databases per instance is 100, so 3 pull requests at the same
time can exceed the limit.
With this change each integration test queries the list of instances for
the project, and then selects one of them at random to run the test. We
will configure several instances in the project used to run the CI
builds, giving us enough bandwidth to run multiple PRs simultaneously.
This is another mitigation for #329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> chore: run integration tests in random instance.

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/session_holder.h
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/internal/transaction_impl_test.cc
- google/cloud/spanner/testing/matchers.h
- google/cloud/spanner/transaction.cc
- google/cloud/spanner/transaction_test.cc
This makes "no session" a distinct case (nullptr) instead of being a
special case inside SessionHolder. Now if SessionHolder exists, the
session_name() is always valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/507)
> Wrap SessionHolder in a unique_ptr

- google/cloud/spanner/read_partition.cc
- google/cloud/spanner/read_partition.h
Additional comments on keeping the current implementation are attached to the issue.
related to #409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/593)
> chore: add ReadPartition constructor from proto

- ci/kokoro/windows/CMakeLists.txt
- ci/kokoro/windows/build-project.ps1
- ci/kokoro/windows/build.bat
- ci/kokoro/windows/common.cfg
Also enable integration tests by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/604)
> test: Fix integration tests on Windows CMake builds

- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/windows/CMakeLists.txt
- ci/super/external/google-cloud-cpp.cmake
- ci/super/external/googleapis.cmake
Upgrade googleapis to 0.1.5 and google-cloud-cpp to 0.13.0. Those versions
support CMake 3.15, which is starting to appear in more places (e.g. my
macOS laptop :grin: )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/605)
> chore: upgrade google-cloud-cpp and googleapis

- README.md
- ci/generate-badges.sh
I made a mistake in the script, it generated an extra quote character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/611)
> doc: Remove spurious quote in README.

- ci/kokoro/windows/build-project.ps1
- ci/kokoro/windows/build.bat
- ci/kokoro/windows/common.cfg
Also enable the integration tests by default
Fixes #601 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/615)
> Fix integration tests on Windows CMake builds.

- google/cloud/spanner/internal/database_admin_retry.cc
- google/cloud/spanner/internal/database_admin_retry.h
- google/cloud/spanner/internal/instance_admin_retry.cc
- google/cloud/spanner/internal/instance_admin_retry.h
- google/cloud/spanner/internal/retry_loop.h
- google/cloud/spanner/internal/retry_loop_test.cc
gRPC requires a newly minted grpc::ClientContext for each RPC, and
without assignment operators (no move, no copy) the only way is to
actually create a new instance in the middle of the loop.
Therefore passing a `grpc::ClientContext` has no effect, and we should
not even have that argument in `RetryLoop()`.
Fixes #490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/617)
> bug: create new grpc::ClientContext for each RPC

- ci/kokoro/docker/build-in-docker-bazel-dependency.sh
- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/install/build.sh
- ci/kokoro/macos/build-bazel.sh
- ci/kokoro/windows/bazel/build.bat
- google/cloud/spanner/instance_admin_client.cc
- google/cloud/spanner/instance_admin_client.h
- google/cloud/spanner/instance_admin_client_test.cc
- google/cloud/spanner/instance_admin_connection.cc
- google/cloud/spanner/instance_admin_connection.h
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/integration_tests/README.md
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/internal/instance_admin_retry.cc
- google/cloud/spanner/internal/instance_admin_retry.h
- google/cloud/spanner/internal/instance_admin_stub.cc
- google/cloud/spanner/internal/instance_admin_stub.h
- google/cloud/spanner/mocks/mock_instance_admin_connection.h
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/testing/mock_instance_admin_stub.h
Fixes #522 
Please note that this is the first operation that is retried (or not) depending on the contents of the request.  `SetIamPolicy()` is idempotent only if `etag()` is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/618)
> feat: implement InstanceAdminClient::SetIamPolicy

- ci/kokoro/docker/publish-refdocs.cfg
Sorry! I believe that this is the last fix for the publishing job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/636)
> docs: Add the service account to the publish-refdocs job

- google/cloud/spanner/connection.h
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/mocks/mock_spanner_connection.h
BREAKING CHANGE: This struct has been renamed, so any code using this
struct will need to be updated. However, it's unlikely that anyone is
using this now.
Fixes: #584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/650)
> chore!: Fixes inconsistent naming of the Batch DML params struct.

- google/cloud/spanner/database.cc
- google/cloud/spanner/database.h
- google/cloud/spanner/database_admin_client.cc
- google/cloud/spanner/database_test.cc
- google/cloud/spanner/instance.cc
- google/cloud/spanner/instance.h
- google/cloud/spanner/instance_test.cc
- google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
- google/cloud/spanner/samples/samples.cc
BREAKING CHANGE: This PR removes renames some accessors like
`InstanceId` -> `instance_id` due to their trivial nature now (style
guide). It also removes some methods like `Database::ParentName()`,
which is now replaced by `Database::instance()`.
Fixes: 586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/652)
> chore!: Implements Database in terms of Instance

- ci/test-install/spanner_install_test.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/result_set.h
- google/cloud/spanner/result_set_test.cc
- google/cloud/spanner/row.h
- google/cloud/spanner/row_parser.h
- google/cloud/spanner/row_parser_test.cc
- google/cloud/spanner/row_test.cc
- google/cloud/spanner/samples/mock_execute_sql.cc
- google/cloud/spanner/samples/samples.cc
BREAKING CHANGE: `ResultSet::Rows` used to be a variadic template that
took the individual C++ types for each row. With this change that
function is now a template with one parameter, which must be a
`Row<...>` type.
Some reasons for this change:
* Our code is simpler when we minimize the functions that need to be
variadic. Instead of making a bunch of functions variadic, we should use
the `Row` class, which handles all the variadic stuff.
* Using a type named "Row" seems more sensible when we're talking about
a "row" than does a sequence of C++ types. That is, bundling C++ types
in a `Row<...>` when those types logically represent a "row" seems like
a readability win.
* A sequence of bare C++ types cannot be aliased, so they need to be
repeated wherever they're needed.
* Spelling all the …
> feat: Changed RowParser to require a Row<Ts...> template param

- google/cloud/spanner/CMakeLists.txt
TIL: Use the macro name for the runtime install directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/658)
> bug: fix runtime install directory

- google/cloud/spanner/CMakeLists.txt
TIL: we can make it easier for package maintainers to create separate
packages for development vs. runtime if we use named components for
the library install directories. With CMake 3.5, however, we need to
use a secondary `install()` command for the libFoo.so.X.Y.Z link (aka
the NAMELINK_ONLY install)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/659)
> feat: support install components for the library

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/internal/retry_loop_test.cc
- google/cloud/spanner/retry_policy.h
- google/cloud/spanner/retry_policy_test.cc
We only want to retry requests on kUnavailable and kResourceExhausted,
and we want to re-run transactions only on kAborted.
Fixes #666 and fixes #529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/667)
> feat: use separate policies for retry vs. rerun

- google/cloud/spanner/internal/instance_admin_logging.cc
- google/cloud/spanner/internal/instance_admin_logging.h
- google/cloud/spanner/internal/instance_admin_logging_test.cc
- google/cloud/spanner/internal/instance_admin_metadata.cc
- google/cloud/spanner/internal/instance_admin_metadata.h
- google/cloud/spanner/internal/instance_admin_metadata_test.cc
- google/cloud/spanner/internal/instance_admin_stub.cc
- google/cloud/spanner/internal/instance_admin_stub.h
- google/cloud/spanner/testing/mock_instance_admin_stub.h
Adding remaining stubs first before working on the higher layer because it's easier to write integration tests at once with the later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/690)
> feat: implement remaining stubs on InstanceAdminClient.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/partial_result_set_reader.h
- google/cloud/spanner/internal/partial_result_set_source.cc
- google/cloud/spanner/internal/partial_result_set_source.h
- google/cloud/spanner/internal/partial_result_set_source_test.cc
- google/cloud/spanner/internal/spanner_stub.cc
- google/cloud/spanner/spanner_client.bzl
Wrapping the `grpc::ClientReadInterface<>` makes it easier to write
tests and to then refactor the code to do retries.
Part of the work for #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/692)
> cleanup: wrap PartialResultSet streaming RPC

- ci/kokoro/docker/build.sh
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/instance_admin_client.cc
- google/cloud/spanner/instance_admin_client.h
- google/cloud/spanner/instance_admin_connection.cc
- google/cloud/spanner/instance_admin_connection.h
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/internal/instance_admin_logging.cc
- google/cloud/spanner/internal/instance_admin_logging.h
- google/cloud/spanner/internal/instance_admin_metadata.cc
- google/cloud/spanner/internal/instance_admin_metadata.h
- google/cloud/spanner/internal/instance_admin_stub.cc
- google/cloud/spanner/internal/instance_admin_stub.h
- google/cloud/spanner/mocks/mock_instance_admin_connection.h
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/mock_instance_admin_stub.h
- google/cloud/spanner/testing/pick_random_instance.cc
- google/cloud/spanner/testing/random_database_name.cc
- google/cloud/spanner/testing/random_instance_name.cc
- google/cloud/spanner/testing/random_instance_name.h
With this PR, I introduced basic integration tests and samples for InstanceAdminClient, which create and delete a new instance with a random name, prefixed with `temporary-instance-{DATE}-`.
While these tests are only executed with an environment variable `RUN_SLOW_INTEGRATION_TESTS=yes`, if a random instance created by these tests is picked up by `google::cloud::spanner_testing::PickRandomInstance`, it's going to be problematic.
So, I made a change in `google::cloud::spanner_testing::PickRandomInstance`, now it only picks up the instance prefixed `test-instance-` for isolating instances between normal tests and CRUD tests for `InstanceAdminClient`.
I feel `InstanceAdminClient::CreateInstance` has too many parameters, but I'm somewhat ok with this because I don't expect many people will …
> feat: implement CreateInstance and DeleteInstance on InstanceAdminClient

- google/cloud/spanner/client.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
Since `ConnectionImpl` relies on `std::enable_shared_from_this`, it
should only be allocated and held in a `std::shared_ptr` (otherwise
calling `shared_from_this()` results in an exception). Make its
constructor private and add a factory method that returns a `shared_ptr`
and is the only way to allocate one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/915)
> Ensure ConnectionImpl is allocated via shared_ptr.

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/create_instance_request_builder.h
- google/cloud/spanner/create_instance_request_builder_test.cc
- google/cloud/spanner/instance_admin_client.cc
- google/cloud/spanner/instance_admin_client.h
- google/cloud/spanner/instance_admin_connection.cc
- google/cloud/spanner/instance_admin_connection.h
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
* BREAKING CHANGE: changed the function signature of InstanceAdminClient::CreateInstance()
fixes #931 
The builder forces you to provide `Instance` object and Spanner Config name when constructing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/933)
> feat!: implement CreateInstanceRequestBuilder

- ci/kokoro/docker/build-in-docker-cmake.sh
This prevents the issue in googleapis/google-cloud-cpp#2163.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/937)
> bug: fix flaky builds due to ccache initialization

- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
Part of preparing for #387 
BREAKING CHANGE: This PR removes the `AddRow(Row<Ts...>)` member function on the WriteMutation API because the `Row<Ts...>` type will be removed. In place of this method there is now an `AddRow(std::vector<Value>)` method. This change enables a new feature, which is that callers can now construct Mutations from `Value` objects, which they could not previously.
Note that some of the refactoring in the integration tests exists as an intermediate step. Once the full "select *" refactoring is finished (#387), much of the integration test code could be cleaned up more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/938)
> feat!: Removed Row<> from mutations API

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
- google/cloud/spanner/integration_tests/throughput_benchmark.cc
This benchmark just measures how many reads and write operations per
second we can execute using the client library, with both a single
`spanner::Client` and using one per thread.
This is the first version, it only measures the throughput for insert
mutations (but not DML statements), and for `SELECT` queries (but not
`Read()` calls). Those other measurements will be added later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/928)
> feat: initial version of throughput benchmark

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/doc/spanner-mocking.dox
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/mocks/mock_spanner_connection.h
- google/cloud/spanner/result_set.h
- google/cloud/spanner/result_set_test.cc
- google/cloud/spanner/samples/samples.cc
BREAKING CHANGE: Completes refactoring and removal of ResultSet in favor of more
specific result return types. Profiling methods and result types to be added in a subsequent
PR. Possible combining of ReadResult and ExecuteQueryResult types deferred to a future
PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/935)
> feat!: Use ReadResult instead of ResultSet; remove ResultSet

- google/cloud/spanner/README.md
Note I also added the v0.1 notes from the releases page which were previously missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/939)
> update release notes [skip ci]

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/944)
> doc: Add example PR for bumping spanner version numbers.

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
- Add options to tune its behavior (these will eventually have to be
user-visible, but let's make them private for now).
- add `min_sessions` to the pool at construction time.
- when the pool is exhausted, add `min_sessions` more sessions to the
pool (subject to the `max_sessions` limit.
- we do not yet refresh or delete sessions.
(this is independent of #924 although CreateSessions() will always return 1 session until it's checked in - that is not an issue since it's permitted to return fewer sessions than requested).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/925)
> Start implementing the real SessionPool.

- WORKSPACE
- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/windows/CMakeLists.txt
- ci/super/CMakeLists.txt
- ci/super/external/google-cloud-cpp-common.cmake
- ci/test-install/WORKSPACE
- google/cloud/spanner/BUILD
- google/cloud/spanner/doc/spanner-main.dox
- google/cloud/spanner/integration_tests/BUILD
- google/cloud/spanner/samples/BUILD
Declare independence from the Cloud Bigtable and Google Cloud Storage
clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/940)
> cleanup: depend on google-cloud-cpp-common

- ci/kokoro/docker/publish-refdocs.sh
Theoretically it will work, but there's no easy way to test it before the actual release process.
Maybe we can backport this change and try this with the v0.2.x branch?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/947)
> fix: fix branch detection in the document publishing script

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
fixes #929 
I've get kept the implementation similar to the streaming rpc as I believe there may be some opportunity to factor out common code as I add the ProfileQuery and ProfileDml methods in a separate PR.
I'm unsure if ExecuteDml needs to support Begin Transaction functionality, so I left it in for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/952)
> refactor: use non-streaming RPC for ExecuteDml

- WORKSPACE
- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/install-bazel.sh
- ci/kokoro/Dockerfile.centos
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- ci/test-install/WORKSPACE
- google/cloud/spanner/keys.h
Install Bazel 1.0 for the builds. We need a newer version of gRPC to
compile with this version of Bazel, so change that too.  Likewise, it
seems that some of the Bazel rules we use (indirectly) depend on
features of `git` that are not available on CentOS:7. I chose to move
the GCC-4.8 build to CMake instead of debugging those problems.
Fixes #950 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/951)
> chore: upgrade to Bazel 1.0

- google/cloud/spanner/internal/partial_result_set_source.cc
- google/cloud/spanner/internal/partial_result_set_source.h
In preparation for #387 we need to get ready for the partial result set source to return a full "row" (i.e., a `vector<Value>`) at a time. This refactoring is an attempt to break up an upcoming huge PR into a a slightly smaller ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/959)
> refactor: prepare for "SELECT * ..." changes

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/background_threads.h
- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/connection_options_test.cc
- google/cloud/spanner/internal/background_threads_impl.cc
- google/cloud/spanner/internal/background_threads_impl.h
- google/cloud/spanner/internal/background_threads_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
This change introduces an interface to represent the background
thread(s) used by a connection. I included two implementations in this
PR, one that automatically creates a single background thread, and
another that uses one or more threads provided by the application.
The ConnectionOptions class provides a factory for `BackgroundThreads`,
for those (we expect few) applications that will want to control the
background threads.
This fixes #606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/955)
> feat: configurable strategy for background threads

- .bazelignore
Adds `.bazelignore` file to make `bazel build ...` work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/965)
> chore: makes bazel build ... work

- cmake/EnableDoxygen.cmake
- google/cloud/spanner/internal/tuple_utils.h
- google/cloud/spanner/internal/tuple_utils_test.cc
Now that `Row<...>` is no longer a variadic template, we can now simplify the `internal::ForEach` function to restrict it to only working with `std::tuple` rather than any tuple-like object. This allows us to remove the `GetElement` extension point, which is not used anywhere anymore.
I also added an `IsTuple<T>` metafunction, which I need in my next PR. It's pretty straight-forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/970)
> chore: simplifies tuple_utils; adds IsTuple metafunction

- google/cloud/spanner/row.cc
- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
This PR is part of #387 
This PR adds two iterator classes and one range class:
- `RowStreamIterator` -- Consumes a "stream" of `Row` objects. Each successively returned `Row` is wrapped as a `StatusOr<Row>`. Users will rarely/never directly use this class, but it's needed to enable other things (like range-for iteration).
- `TupleStreamIteartor<T>` -- Wraps a `RowStreamIterator`, and parses each successive `Row` into a `std::tuple<...>`, and yields it as a `StatusOr<std::tuple<...>>`. Users will rarely/never directly use this class, but it's needed to enable other things.
- `StreamOf<Tuple>` -- A "range" of `TupleStreamIterator<T>`. This is a class that users will (eventually) directly use. Users may use this class as follows:
```cc
auto rows = client.Read(...);
using RowType = …
```
> feat: adds row iterators (and friends); not yet used

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
This bug showed up when `TupleStreamIterator<>` was consuming a stream
that  not just failed to parse, but totally failed to return any `Row`
data at all. In that case, the input iterator's `*it_` held a `StatusOr`
that was not OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/973)
> fix: fixes a bug in TupleStreamIterator<>

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/connection.h
- google/cloud/spanner/doc/spanner-mocking.dox
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/partial_result_set_source.cc
- google/cloud/spanner/internal/partial_result_set_source.h
- google/cloud/spanner/mocks/mock_spanner_connection.h
- google/cloud/spanner/query_partition.h
- google/cloud/spanner/samples/mock_execute_query.cc
- google/cloud/spanner/transaction.h
fixes #930 
added ProfileQuery and ProfileDml to handle query_mode == PROFILE
added AnalyzeSql to handle query_mode == PLAN
created issue #960 to track adding sample code (this PR is big enough)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/961)
> feat: add Profile and Analyze methods

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
- google/cloud/spanner/integration_tests/throughput_benchmark.cc
- google/cloud/spanner/mutations.h
- google/cloud/spanner/samples/samples.cc
Replace `g:c:s:RunTransaction()` with a new `g:c:s:Client::Commit()`
overload.  This is similar to the existing `Commit()`, but you
specify how to create the mutations, instead of passing them
directly, which is what is needed to create the rerun loop.
The "mutator" callback no longer receives the target `Client` as
an argument because many mutators don't need it.  If you want
a client in your callback, you will need to bind it yourself.
The `Transaction::ReadWriteOptions` have been removed as there
are no options, and being able to preallocate RW transactions
pretty much requires that remains the case.
Session affinity over reruns is still to be addressed.
BREAKING CHANGE
Fixes #557.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> feat!: Replace RunTransaction() with Client::Commit(functor)

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/doc/spanner-mocking.dox
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/throughput_benchmark.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/mocks/mock_spanner_connection.h
- google/cloud/spanner/results.cc
- google/cloud/spanner/results.h
- google/cloud/spanner/results_test.cc
- google/cloud/spanner/samples/mock_execute_query.cc
- google/cloud/spanner/samples/samples.cc
Fixes #977 
Renames `QueryResult` -> `RowStream` for the reasons described in #977. Also standardized on variable naming: The variable used to store the results of a `client.Read(...)` or `client.ExecuteQuery(...)` is always named `rows` now, which I think reads nicely in the code.
This PR is a semantic no-op. Only a rename.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/978)
> chore!: renamed QueryResult -> RowStream

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Fixes #422
Changes `Value::get<T>()` to efficiently move `std::string` values out
of the proto and directly to the caller. `std::string` is the only type
that can do this because it's the only type which is exactly the same in
the proto and outside of it. All other types require some type of
decoding, which necessarily requires some amount of copying from the
proto out to the caller.
Note: the unit tests verifying this behavior rely on unspecified behavior of std::string. Specifically that a moved-from large string ends up empty. This is not guaranteed, but it *appears* to the true in all cases that I've seen. So we rely on this behavior in the unit test. If this turns out to not be true on some platform, we'll have to adjust the unit tests. I've commented the tests about this.
---
This …
> feat: adds efficient move support to Value::get<string>()

- google/cloud/spanner/database_admin_connection_test.cc
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_install_test.cc
- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
- google/cloud/spanner/samples/mock_execute_query.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/testing/pick_random_instance.cc
In many cases we were using range-for loops like `for (auto row : x)`,
which makes a copy in `row` for each element. In most cases, we do not
want/need this copy. If we only read from the value, we want a `const&`.
if we want to move from the element, we may want a non-const reference.
Only rarely would we actually want a copy.
This PR updates all the cases that I could find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/981)
> chore: avoids range-for copies when possible

- google/cloud/spanner/client_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_install_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/samples/samples.cc
By convention, we name the result of `Client::Read` and
`Client::ExecuteQuery` `rows`. There were a few places where this wasn't
happening, mostly be because the variable was declared on a different
line from the function call, so my previous greps missed these.
No semantic change. Just a rename.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/982)
> chore: a little more naming cleanup for consistency

- ci/etc/install-config.sh
- ci/etc/kokoro/install/project-config.sh
- ci/etc/kokoro/install/run-installed-programs.sh
- ci/etc/publish-refdocs.sh
- ci/etc/repo-config.sh
This PR introduces the configuration files to automatically generate
`ci/kokoro/install`. I decided to *not* generate that directory in the
same PR so folks can examine the configuration files and decide if they
are worth the trouble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/974)
> ci: configure generator for ci/kokoro/install

- google/cloud/spanner/client.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/mocks/mock_spanner_connection.h
- google/cloud/spanner/query_partition.cc
- google/cloud/spanner/query_partition.h
- google/cloud/spanner/query_partition_test.cc
- google/cloud/spanner/samples/mock_execute_query.cc
BREAKING CHANGE: This rename makes sense since we no longer have an
"ExecuteSql" function, and shorter name is clearer.
Fixes: #962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/986)
> chore!: rename ExecuteSqlParams -> SqlParams

- ci/etc/kokoro/install/run-installed-programs.sh
- ci/kokoro/define-docker-variables.sh
- ci/kokoro/install/build.sh
We are trying to make the build scripts automatically generated, this PR
makes the `ci/kokoro/install/build.sh` script look more like the script
in g-c-cpp-common, so we can automatically generate it soon-ish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/987)
> ci: make install/build.sh more like other repos

- google/cloud/spanner/mutations.h
- google/cloud/spanner/mutations_test.cc
Fixes: #379 
Most of the testing for this is done via `static_assert`s that ensure that a chain of method calls results in a call to `.Build()` that returns an rvalue. That ensures that the right functions are being called. Then I actually call the code and test that it works, but this part of the test doesn't really verify that moving happened, just that the code path works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/989)
> feat: add efficient move support to mutation builder temporaries

- ci/kokoro/docker/build-in-docker-cmake.sh
- cmake/GoogleCloudCppSpannerFunctions.cmake
- google/cloud/spanner/CMakeLists.txt
The install rule was creating unexpected directories in the
`$PREFIX/include` path, such as
`google/cloud/spanner/integration_tests`. Fixed the install rules to
only install the headers associated with specific targets.
Fixes #926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/993)
> bug: only install the required headers

- .github/ISSUE_TEMPLATE/bug_report.md
This is using the "new workflow" from the github UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/998)
> chore: add issue template for spanner

- ci/kokoro/docker/build-in-docker-cmake.sh
- cmake/GoogleCloudCppSpannerFunctions.cmake
- google/cloud/spanner/CMakeLists.txt
Fixes #571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/997)
> bug: install the headers for mocking

- google/cloud/spanner/internal/background_threads_test.cc
This should at the very least reduce the flakiness of the test. It was
failing because the thread handling a callback *can* be the same thread
if the event (in the test "the timer") is already satisfied when the
callback is registered.
Fixes #995 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/996)
> bug: remove flaky test

- .bazelrc
- INSTALL.md
- ci/test-readme/generate-install.sh
gRPC requires an additional flag to compile with Bazel. I chose to
both document this *and* set it on our .bazelrc. Note that users will
need to set this flag on their own .bazelrc.
Fixes #1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1005)
> docs: document additional flags needed for macOS

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/single_row_throughput_benchmark.cc
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
Part of the work for #539. Implements the first benchmark to compare
throughput vs. number of threads. In this iteration just for `InsertOrMutate`
mutations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1007)
> feat: a benchmark for single row throughput

- google/cloud/spanner/samples/samples.cc
We recommend that users call the Commit() function that reruns the
mutating functor after a read-write transaction aborts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1009)
> style: use the re-running Commit() in the samples

- google/cloud/spanner/integration_tests/single_row_throughput_benchmark.cc
Change the `single_row_throughput_benchmark` to
support a benchmark for `Read()` requests that fetch
a single row. The benchmark measures the throughput
with different numbers of threads and clients.
This PR also changes the benchmark to run very short
versions of all the experiments when running without any
arguments (for example as part of the integration test). This
checks that the benchmark does not have obvious bugs.
This is part of the work for #539.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1011)
> feat: implement benchmark for read throughput

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
Remove the circular dependency between `ConnectionImpl` and
`SessionPool`. The latter can now make RPCs directly instead of
having to call back through the `SessionManager` interface.
The `SessionHolder` deleter also now calls directly into `SessionPool`
so we don't need to forward those calls from `ConnectionImpl`.
I also removed the tests where `BatchCreateSessions` returned
`RESOURCE_EXHAUSTED` since we learned from spanner team that will never
happen (since there are no longer server-side session limits), and the tests
conflicted with our retry policy.
Part of #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1022)
> feat: split `ConnectionImpl` and `SessionPool` cleanly

- google/cloud/spanner/database_admin_connection.cc
- google/cloud/spanner/instance_admin_connection.cc
- google/cloud/spanner/internal/connection_impl.h
Making the policy member variables `const` ensures that we call `clone` prior to using them, so we can't perturb the initial state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1019)
> cleanup: ensure policies are not modified before use

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
This will facilitate some upcoming Session/Stub-related changes.
I also added another helper to help build a result with a `StatusOnlyResultSetSource`.
One subtler change is instead of doing `Session` preparation inside `ExecuteSqlImpl` we now do it in its two callers (`CommonQueryImpl` and `CommonDmlImpl`), that will also facilitate additional changes involving stubs (which are used in the body of the latter two methods).
Part of #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1037)
> refactor: factor Session preparation to a helper

- ci/kokoro/install/build.sh
Regenerate ci/kokoro/{install,readme} from the latest version in
g-c-cpp-common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1045)
> ci: fix Docker image caching

- google/cloud/spanner/benchmarks/CMakeLists.txt
My previous refactoring was wrong, I use the wrong variable, which went
undetected because things that are not built do not generate errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1044)
> bug: fix list of benchmarks in build

- google/cloud/spanner/internal/session_pool.h
This should have been deleted in a previous PR but I must have missed
it. There are no more references to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1047)
> cleanup: delete unused `SessionManager` interface

- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
I added a comment and also renamed it to MakeLimitedRetryConnection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1048)
> cleanup: clarify the purpose of MakeTestConnection

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
We no longer need the `EqualTypeProtoIgnoringNames()` function, which was using protos `MessageDifferencr`, which is relatively slow. Instead, we can much more quickly check the fields of the proto to see if they match the user-specified type `T`. 
This new code also matches the tag-dispatched structure of most of the rest of `Value`'s implementation, so it fits in well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1053)
> refactor: replaces proto MessageDifferencer with direct functions to check proto type

- google/cloud/spanner/benchmarks/CMakeLists.txt
- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/spanner_client_benchmarks.bzl
Change the CPU overhead benchmark to fetch multiple rows per
query, which amortizes the RPC overhead.
I made several "cleanups" because the code had a lot of duplication
between the "using stubs" vs. "using client" cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1051)
> feat: measure CPU for multiple rows per query

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/client.cc
- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/connection_options_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
- google/cloud/spanner/internal/spanner_stub.cc
- google/cloud/spanner/internal/spanner_stub.h
- google/cloud/spanner/internal/spanner_stub_test.cc
Note that `Client` might create multiple channels but the `SessionPool`
only uses the first one right now. I'll add proper support for multiple
channels in a subsequent change but wanted to get some of the more
mechanical parts out of the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1050)
> feat: add some plumbing to enable multiple channels

- ci/kokoro/install/common.cfg
The necessary credentials were missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1061)
> ci: actually enable caching for install builds

- google/cloud/spanner/query_partition.h
- google/cloud/spanner/read_partition.h
- google/cloud/spanner/samples/samples.cc
Fixes: #541 
I *think* this fixes #541. I added a `@note` to all the relevant places in the docs. I also added a comment to the example code, and renamed the `Send()` function to make it clear that it's a string of binary data. I suspect this should make it clear enough.
Do you think we need more than this, or should this make it clear enough?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1067)
> docs: clarifies that serialized partitions are strings of binary data

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
- google/cloud/spanner/samples/samples.cc
Fixes: #386
This is just a convenience, but it seems nice in some cases. I found on
example that could use this in our current code. I also have another one
in an upcoming PR where I would like this.
Do we like this? Or do we have a better API to consider?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1074)
> feat: add function to get a single row from a range

- google/cloud/spanner/client.cc
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/transaction_impl.h
- google/cloud/spanner/transaction.cc
- google/cloud/spanner/transaction.h
- google/cloud/spanner/transaction_test.cc
Fixes #472.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1079)
> fix: execute each rerun of an aborted transaction in the same session

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
- google/cloud/spanner/internal/date.cc
- google/cloud/spanner/internal/date_test.cc
- google/cloud/spanner/testing/database_environment.cc
The year is required to be 0-padded to 4 digits, the month and date
padding seems to be optional.
Introduce a new integration test to verify data types can be written and
read back.
Fixes #1083
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1085)
> bug: fix year formatting in spanner::Date

- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
* SessionPool now utilizes all channels that are given to it, creating new sessions on the least loaded channel.
* The default number of channels created has been changed to 4.
* Refactor Session creation and add to pool logic.
* Add some tests that use multipe channels.
* Rework some tests that depended on the order of returned Sessions.
Part of #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1063)
> feat: support multiple channels in SessionPool

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Add benchmarks to measure the CPU overhead of reading different data
types, specifically: `BOOL`, `BYTES(1024)`, `DATE`, `FLOAT64`, `INT64`,
`STRING(1024)`, and `TIMESTAMP`.
This fixes #1017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1084)
> feat: benchmark CPU overhead with different data types

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
* `max_sessions` is now `max_sessions_per_channel`
* we're not going to be using `write_sessions_fraction`, so remove it.
Note I also flipped the precedence of `min_sessions` and (`max_sessions_per_channel` * the number of channels) - the latter now takes precedence, just for simplicity; I don't think it matters that much because it's a misconfiguration.
Part of #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1089)
> feat: update the pool options to match the design

- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
- google/cloud/spanner/samples/samples.cc
After some discussion with the local folks, we decided to change the semantics and name of `GetCurrentRow` that was added in #1074. Previously `GetCurrentRow` would return the first row in a range that might potentially contain multiple rows. The observation is that those may not be the best or safest semantics for callers.
The use case we're trying to address is when a callers does a query/read and they know that only one row should be returned. Maybe they used `LIMIT 1`, or maybe they specified a primary key to guarantee this. In any case, if they know that only one result can be returned, it would be nice to let them conveniently access that one row without having to create a loop, break out, etc.
The problem with `GetCurrentRow` was that _if_ the row range happened to have _more_ than …
> feat: change GetCurrentRow to GetSingularRow

- google/cloud/spanner/client_test.cc
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/database_admin_connection_test.cc
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/database_admin_metadata_test.cc
- google/cloud/spanner/internal/instance_admin_metadata_test.cc
- google/cloud/spanner/internal/metadata_spanner_stub_test.cc
- google/cloud/spanner/internal/partial_result_set_resume_test.cc
- google/cloud/spanner/internal/session_pool_test.cc
It is not necessary to `Invoke()` a lambda in the context of `WillOnce()`
or `WillRepeatedly()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1091)
> cleanup: remove unnecessary calls to testing::Invoke()

- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/testing/database_environment.cc
Part of #1096
This PR adds DataType integration tests for all the non-aggregate
spanner value types that. I'll add the array and struct types in a
follow up PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1097)
> feat: add more DataType tests

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
we only `source` that script so it doesn't need to be executable, only
readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1099)
> drop executable requirement for INTEGRATION_TEST_CONFIG

- google/cloud/spanner/bytes.cc
- google/cloud/spanner/bytes.h
- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
Now with more move support.
Fixes #1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1104)
> feat: optimize passing Bytes to Value

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/doc/spanner-main.dox
- google/cloud/spanner/samples/samples.cc
Add an overload for `spanner::MakeConnection()` which allows users to
override the retry and backoff policies. Implement an example showing
how to use this overload.
Fixes #244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1111)
> feat: allow users to configure retry policies

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Add new benchmarks to measure the CPU overhead (if any) of making
`UPDATE` queries via the client library vs. the raw gRPC code. The
benchmarks can measure the overhead for different data types.
Fixes #1016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1095)
> feat: benchmark CPU overhead for UPDATE

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
The smoke tests are performing too many admin operations (basically
CREATE TABLE), to the point where they exceed the project quota and the
integration tests flake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1120)
> bug: disable benchmark smoke tests

- .clang-format
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1122)
> fix: tell clang-format to leave doxygen @copydoc directives alone

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/session_pool_options.h
- google/cloud/spanner/spanner_client.bzl
Moves `SessionPoolOptions` out of the `internal` namespace,
and adds a `std::map<std::string, std::string> labels` field.
Plumbs those labels through to the `BatchCreateSessions()`
call.
Fixes #421.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1109)
> feat: add SessionPoolOptions with labels to MakeConnection()

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Use a single operation to create the database and all the tables that
might be needed. This reduces the number of admin operations in the
smoke tests by a factor of 28.
Because each smoke test then becomes "fast" (a couple of seconds) there is
no need to parallelize them, which simplifies a lot of the locking strategy.
Fixes #1119 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1125)
> bug: reduce number of admin operations for smoke test

- google/cloud/spanner/internal/time.cc
- google/cloud/spanner/internal/time.h
- google/cloud/spanner/internal/time_format.cc
- google/cloud/spanner/internal/time_format.h
- google/cloud/spanner/internal/time_format_test.cc
- google/cloud/spanner/internal/time_test.cc
Introduce versions of `internal::FormatTime()` and `internal::ParseTime()`
that do not take a format-specifier string. Instead they only format and
parse _"%Y-%m-%dT%H:%M:%S"_, allowing them to be very specific and fast.  In
particular this allows us to avoid `std::put_time()` and `std::get_time()`
(and we avoid `std::sscanf()` too). Use these to implemented the Spanner
`TimestampToString()` and `TimestampFromString()` conversion functions.
Fixes #1088.
Note: The new, format-specifier-less `internal::FormatTime()` produces a
4-character year when possible (unlike the _"%Y"_ format specifier).
Also introduce formatting and parsing of _"[-+]HH:MM"_ UTC offset fields.
While we will always produce a _"Z"_ offset in `TimestampToString()` for
Spanner, this will enable some refactoring of the …
> bug: optimize Timestamp conversions to/from string

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool_test.cc
- google/cloud/spanner/session_pool_options.h
- google/cloud/spanner/session_pool_options_test.cc
- google/cloud/spanner/spanner_client_unit_tests.bzl
* This makes `SessionPoolOptions` similar to `ConnectionOptions`.
* Setters provide a "Builder" type interface.
* Enforcing constraints has been moved to the class itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1130)
> refactor: make `SessionPoolOptions` a class

- google/cloud/spanner/benchmarks/benchmarks_config.cc
- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Any I/O manipulator that sets a per-stream I/O format flag
is not thread safe, as recent ThreadSanitizer warnings attest.
So, set `std::ios::boolalpha` in the benchmarks before we fork
any threads, rather than during concurrent output operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1128)
> bug: set "sticky" I/O format flags before forking threads

- google/cloud/spanner/client.cc
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/internal/session.h
- google/cloud/spanner/retry_policy.h
This fixes part of #914 
A followup PR will need to have the SessionPool look at this Session::bad() bit and remove it from the pool (or something).
Note: much of this was pair-programmed with @devbww
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1138)
> feat: mark not-found sessions as bad

- INSTALL.md
- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/test-readme/generate-install.sh
Fixes #1131
This regenerates the `INSTALL.md` and Dockerfiles to use the `cmake-out`
directory instead of `/o` like in common. This also adds a blurb at the
beginning on how to obtain spanner so that `$HOME/project` will exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1139)
> docs: use cmake-out directory and add how to obtain spanner

- google/cloud/spanner/internal/time.cc
- google/cloud/spanner/internal/time.h
- google/cloud/spanner/internal/time_test.cc
We don't use `FromProto(google::protobuf::Duration const&)`, and not
having it sidesteps the issue that the result may not be representable
as a `std::chrono::nanoseconds`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1140)
> chore: remove g::protobuf::Duration to std::chrono::nanoseconds conv

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
Part of #914... almost finished with that.
In this PR, all the rpcs in ConnectionImpl check for SessionNotFound errors and when detected they call `session->set_bad()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1141)
> feat: handle session-not-found in all connection_impl methods

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl_test.cc
Fixes #689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1143)
> feat: commit begins transaction if not already begun

- cmake/EnableWerror.cmake
Fixes #671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1150)
> feat: add CMake option to disable -Werror/-WX

- ci/kokoro/docker/build.sh
On SELinux-enabled systems, if the `\$PWD` has any security contexts, mounting
the filesystem can result in permission denied errors. The solution is to
append `:Z` which will have the mounted filesystem share the security contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1149)
> fix: add :Z to volume mount

- google/cloud/spanner/client_test.cc
Add unit tests for two Client::ProfileSql overloads that were
not tested elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1152)
> feat: close coverage gaps in spanner::Client

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Make sure the smoke tests exercise both the client and stubs paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1154)
> feat: fix coverage for benchmark

- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
I've been bitten a few times now by needing to call `shared_from_this()`
in the constructor (which doesn't work because the `shared_ptr` that's
going to hold `this` is not yet constructed), so this splits out code that
might need to do that into `Initialize()` which is called by the factory.
Session creation doesn't have to do it right now but it will, and we'll
also start the background thread processing from there... just wanted to
split this out in the interest of smaller CLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1148)
> refactor: add a factory method for `SessionPool`

- ci/kokoro/windows/bazel/build.bat
- ci/kokoro/windows/build.bat
Before 1.25.0 gRPC sometimes crashes when using the c-ares DNS resolver
on Windows, see grpc/grpc#18461 for more details.
I think this will minimize the problems reported in #1034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1158)
> ci: workaround a bug in gRPC < 1.15.0

- google/cloud/spanner/integration_tests/client_integration_test.cc
A `Commit()` mutator may be re-run, so users need to be careful
with any state shared between runs.  In this case we do not want
to accumulate expected results across re-runs, so clear the vector
of expected rows each time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1163)
> bug: be careful with by-reference captures in a Commit() mutator

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/database_admin_client.cc
- google/cloud/spanner/database_admin_client.h
- google/cloud/spanner/database_admin_client_test.cc
- google/cloud/spanner/iam_updater.h
- google/cloud/spanner/instance_admin_client.cc
- google/cloud/spanner/instance_admin_client.h
- google/cloud/spanner/instance_admin_client_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client.bzl
Adds functions to DatabaseAdminClient and InstanceAdminClient that run a
optimistic concurrency control (OCC) loop for IAM updates. That makes
the customer code a bit easier to write and less error prone. This is
analogous to the Commit() loops for the spanner::Client.
This fixes #613 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1162)
> feat: optimistic concurrency control loop for IAM

- google/cloud/spanner/client.cc
The intent was to ensure the number of channels was "at least one",
but instead actually made it "at most one".
There is no test for this because client_test uses the Client
constructor directly. We should try to add one, but let's fix
this obvious bug first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1169)
> bug: number of channels was inadvertently limited to 1

- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
Track the number of threads waiting for a `Session` to ensure we always
notify properly; the prior implementation had race conditions that
could lead to a thread waiting forever even when a `Session` was
available (see #1000 for details).
I also removed the workaround for this bug in the benchmark. With
the workaround removed, I ran the benchmark using the flags below,
both with and without the `SessionPool` fix. Without the fix it
hangs reliably, with the fix it never hangs.
```
.build/google/cloud/spanner/benchmarks/single_row_throughput_benchmark \
--project=${GOOGLE_CLOUD_PROJECT} \
--instance=${GOOGLE_CLOUD_CPP_SPANNER_INSTANCE} \
--table-size=1000 \
--minimum-clients=1 --maximum-clients=1 \
--minimum-threads=1000 --maximum-threads=1000 \
--iteration-duration=2 --samples=100 \ …
```
> fix: avoid deadlock waiting for Session allocation

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Removes the workaround for #1000 from the multiple rows benchmark.
Since we're no longer adjusting min, and the `Config` class already validates
`min_clients <= max_clients` we no longer need to do it here.
Fixes two small bugs in the existing code (AFAICT):
* `ClientCount` would usually (always?) return `min_clients` because
`min_clients <= max_clients` is generally true.
* No need to subtract 1 from `max_clients` when generating a random number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1175)
> fix: clean up / fix ClientCount logic

- google/cloud/spanner/benchmarks/benchmarks_config.cc
- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
If the user specifies a non-empty `--database <database_name>` on the command
line, it will be re-used across runs. The database will be created and
populated if it doesn't already exist (i.e. on the first run) but it
will not be dropped at the end of the run as it normally would be.  This
saves a lot of setup time if you're running the benchmark repeatedly.
Otherwise, the behavior is unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1174)
> feat: allow re-using a database across benchmark runs

- google/cloud/spanner/benchmarks/benchmarks_config.cc
- google/cloud/spanner/benchmarks/benchmarks_config_test.cc
- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
The `single_row_throughput_benchmark` doesn't use `getrusage()`, so
checking for it in `Config` unnecessarily precludes it from running
(i.e. when using `bazel` builds).
Instead, check in `multiple_rows_cpu_benchmark` which actually does care.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1186)
> fix: only check for per-thread rusage in the benchmark that requires it

- google/cloud/spanner/timestamp.cc
- google/cloud/spanner/timestamp_test.cc
* Add test cases for some previously unexercised code paths
* Remove one always-unreachable overflow-detection code path
* Another overflow-detection code path is unreachable when
`tm_year` is only 32-bits (which is usually the case), so we
can't hit 100% coverage
* Fix one bug with creating a `Timestamp` from a `time_point`
with sub-nanosecond precision, and add test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1190)
> fix: complete test coverage for g:c:spanner::Timestamp

- doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1191)
> chore: releases should use release.sh now

- google/cloud/spanner/benchmarks/benchmarks_config.cc
- google/cloud/spanner/benchmarks/benchmarks_config.h
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
* factor Client creation code out to a helper
* make `InsertOrUpdateExperiment` use `DefaultPRNG` like the others
* remove superfluous mutex from `UpdateDmlExperiment::RunIteration`
* start to migrate from `minimum/maximum_clients` to `_channels`
Part of #1193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1194)
> feat: use 1 client with multiple channels for the benchmark

- google/cloud/spanner/client.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1198)
> docs: specify how Commit(mutator, ...) handles exceptions

- cmake/EnableDoxygen.cmake
The classes in the benchmarks are not interesting for the user-facing
reference documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1208)
> doc: exclude benchmarks for doxygen docs

- google/cloud/spanner/samples/samples.cc
This should unblock our doc writer.
Part of #1217, #1218, #1219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1220)
> doc: add skeletons for *_with_timestamp_column

- google/cloud/spanner/timestamp.h
- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
Part of #1217, #1218, #1219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1225)
> feat: add CommitTimestamp support

- README.md
- ci/test-readme/generate-readme.sh
- google/cloud/spanner/samples/BUILD
Update the README.md generate to include instructions to build the
and run the examples using Bazel.
This PR changes the target name from
`//google/cloud/spanner/samples:spanner_client_samples`
to 
`//google/cloud/spanner/samples:samples`
The latter seems easier to explain.
This fixes #1133 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1228)
> doc: document how to run samples using Bazel

- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
Ninja is more strict than Make, building with it can detect bugs in our
CMake files. And while Ninja is not as well-known as Make, it is a
faster builder, and therefore it is somewhat popular as a CMake backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1229)
> ci: configure a CMake+Ninja build

- google/cloud/spanner/samples/samples.cc
When possible use single-line `if(..) throw..` to handler errors, and
avoid introducing `StatusOr` unless we really use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1231)
> cleanup: remove clutter from some samples

- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- super/external/grpc.cmake
Workaround grpc/grpc#21280 by compiling against a specific commit
(without a tag) of the v1.26.x gRPC branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1232)
> ci: use gRPC-1.26.x to workaround a known bug

- google/cloud/spanner/row.h
- google/cloud/spanner/row_test.cc
Single-argument forwarding constructors can hide implicitly generated
copy/move constructors. Even if this issue is avoided with the proper
use of SFINAE, clang-tidy may still complain (incorrectly, I think).
http://clang.llvm.org/extra/clang-tidy/checks/bugprone-forwarding-reference-overload.html
To fix this I renamed the class `StreamOf` -> `TupleStream`. I then
changed its constructor to accept two iterators instead of a single
range. Then I added a `StreamOf<T>()` non-member factory function. This
should make it so our existing uses all continue to work.
So, this really shouldn't be much of an API break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spann …
> fix!: avoid single-arg forwarding c'tor

- google/cloud/spanner/client.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/transaction.h
This fix will silence clang-tidy's `performance-unnecessary-value-param` warning when run on our headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1239)
> chore: silence clang-tidy warning on internal::Visit

- .clang-tidy
Fixes #355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1235)
> chore: enable clang-tidy on our headers

- google/cloud/spanner/results.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1243)
> docs: add summary of result classes

- google/cloud/spanner/transaction.h
For future reference, document the clang-tidy warning suppression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1244)
> chore: explain use of "performance-unnecessary-value-param"

- INSTALL.md
- WORKSPACE
- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/test-install/WORKSPACE
- ci/test-readme/generate-install.sh
- google/cloud/spanner/doc/spanner-main.dox
Upgrade protobuf to 3.11.3, this is needed to build with the latest and
greatest googleapis on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1247)
> ci: upgrade protobuf to v3.11.3

- INSTALL.md
- ci/test-readme/generate-install.sh
- google/cloud/spanner/doc/spanner-main.dox
Use a real release and SHA256 for the `google-cloud-cpp-spanner` release.
Updated `INSTALL.md` with the latest changes.
Many thanks to @agasparovic-sabre for pointing out this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1226)
> doc: fix INSTALL instructions for Bazel

- google/cloud/spanner/client.cc
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/read_partition.cc
https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/connection.h defines the `Connection` interface, which allows us and our customers to mock out the Spanner "backend" for easier unit testing. That interface defines several `FooParms` structs, which hold all the parameters for each of the virtual methods. Most of those structs are normal/trivial structs, i.e., *they do not have constructors*.
However, we do have two structs that have constructors: 
https://github.com/googleapis/google-cloud-cpp-spanner/blob/01f634f75a08dc4cc98949ff0ad2a554100f31d4/google/cloud/spanner/connection.h#L78
and
https://github.com/googleapis/google-cloud-cpp-spanner/blob/01f634f75a08dc4cc98949ff0ad2a554100f31d4/google/cloud/spanner/connection.h#L102
These exist for …
> refactor!: remove c'tors from Connection::* param structs

- google/cloud/spanner/internal/connection_impl_test.cc
Disables -Wmissing-field-initializers in one unit test file to improve
the readability of our test code. Note: This flag is enabled by -Wextra.
More details in the comment in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1264)
> chore: disable warning in test file to simplify code

- google/cloud/spanner/client.cc
- google/cloud/spanner/connection.h
- google/cloud/spanner/query_partition.cc
We're going to be adding a new field to SqlParams fairly soon, so to
prevent an API break later, this PR adds a dummy field in the struct so
that we can take the API breakage now rather than later. The struct
field is named such that users *should* not use it by name, but its
existence should require that it gets default initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1265)
> refactor!: prepare for new field in SqlParams

- google/cloud/spanner/connection.h
- google/cloud/spanner/database_admin_connection.h
- google/cloud/spanner/instance_admin_connection.h
- google/cloud/spanner/row.h
- google/cloud/spanner/session_pool_options.h
Fixed missing documentation for SessionPoolOptions. Fixed documentation
for some of the `*Param` classes, they were picking up the documentation
for the group of classes, not their own docs. Made documentation for
`*Param` consistent. Fixed broken link in `RowStreamIterator` docs,
apparently Doxygen does not expand links in the brief document.
Fixes #1203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1267)
> doc: small tweaks to Doxygen documentation

- INSTALL.md
- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
When installing the library, do not run the unit tests or benchmarks.
This removes two steps from the installation instructions, even the more
difficult platforms have about 10 steps, so 2 steps is a significant
change.
This test theoretically reduces the testing coverage, as it disables unit
tests in a number of platforms. We think the risk is low, as the same unit
tests pass in many other builds, and we are running at least one smoke
test for the `ci/kokoro/install` builds.
This fixes #1216 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1268)
> doc: simplify install instructions

- INSTALL.md
- ci/test-install/WORKSPACE
- ci/test-readme/generate-install.sh
- google/cloud/spanner/doc/spanner-main.dox
We never explained that users need to load a Starlark function to use
`http_archive()`. Also fix the documentation to use the current release,
this will get "stale", but would be still functional and we warn users
to update the version and SHA256 in the comments.
Since I was fixing this I also updated the INSTALL.md file (and its
generator) with the changes from #1252, thanks to @antfitch for proposing
these improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1254)
> doc: improve instructions for WORKSPACE files

- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options.h
- google/cloud/spanner/connection_options_test.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/internal/spanner_stub_test.cc
- google/cloud/spanner/samples/samples.cc
When the `SPANNER_EMULATOR_HOST` environment variable is set, the
endpoint and credentials for data and admin connections are overridden
by `${SPANNER_EMULATOR_HOST}` and `grpc::InsecureChannelCredentials()`
respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1269)
> feat: environment-variable override of the spanner endpoint

- google/cloud/spanner/internal/instance_admin_logging.h
- google/cloud/spanner/internal/instance_admin_metadata.h
- google/cloud/spanner/internal/instance_admin_stub.h
- google/cloud/spanner/testing/mock_instance_admin_stub.h
Even when they are in an anonymous namespace, and especially when
the aliases do not have unique names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1274)
> fix: avoid namespace aliases in header files

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/spanner_client_unit_tests.bzl
This fixes a bug introduced in https://github.com/googleapis/google-cloud-cpp-spanner/pull/1279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1280)
> fix: added connection_options_test back to build

- INSTALL.md
- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- super/external/google-cloud-cpp-common.cmake
Note: `INSTALL_GOOGLE_CLOUD_CPP_COMMON_FROM_SOURCE` is
currently overridden in `ci/etc/kokoro/install/project-config.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1281)
> chore: upgrade dep to g-c-c-common v0.20

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_install_test.cc
- google/cloud/spanner/testing/pick_random_instance.cc
* When the emulator doesn't have the `${GOOGLE_CLOUD_CPP_SPANNER_INSTANCE}`
instance, short-circuit the `InstanceAdminClientTest.InstanceReadOperations`
test, and also don't run the `spanner_client_benchmark_programs`.
* When the emulator doesn't have any instances, make `spanner_install_test`
exit successfully.
* When the emulator doesn't have any "test-instance-*" instances, change
`PickRandomInstance()` to create and return "test-instance-a".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1282)
> feat: more allowances for running integration tests against the emulator

- google/cloud/spanner/connection_options.cc
- google/cloud/spanner/connection_options_test.cc
`${GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT}` can override the
default endpoint `spanner.googleapis.com`.
Fixes #1255.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1283)
> feat: support environment-variable override of default endpoint

- google/cloud/spanner/benchmarks/benchmarks_config_test.cc
- google/cloud/spanner/connection_options_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1284)
> chore: migrate to `testing_util::ScopedEnvironment`

- INSTALL.md
- ci/test-install/WORKSPACE
- ci/test-readme/generate-install.sh
this is a workaround for the version numbers not being auto-updated (#1288)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1290)
> chore: Update release version numbers in `INSTALL.md`

- README.md
- ci/test-readme/generate-readme.sh
It seems that it is necessary to use `bazel test` before `bazel run`
on Windows. Bazel creates a `tw.exe` file during the `test` step, which
is needed (but not created) in the `bazel run` step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1287)
> doc: on Windows run bazel test before bazel run

- google/cloud/spanner/doc/spanner-main.dox
see #1288 
technically this should probably be done in the 0.8.0 branch as well, but not sure it's worthwhile as long as we're cutting one more release before GA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1292)
> doc: update release version/SHA in .dox file

- ci/kokoro/windows/bazel/build.bat
- ci/kokoro/windows/build-project.ps1
gRPC after 1.26.0 (which we use in all our builds) has fixes to allow
running multiple processes on the same directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1316)
> ci: parallelize the integration tests for Windows

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
Treat the exception thrown by the mutator as if the enclosed `Status`
had been returned instead (OK is converted to an "unknown" status).
This allows the transaction to be rerun (when the status is transient).
Fixes #1311.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1320)
> feat: do not rethrow `RuntimeStatusError` from a `Commit()` mutator

- google/cloud/spanner/client.cc
- google/cloud/spanner/client.h
- google/cloud/spanner/client_test.cc
This convenience function saves the user from having to create a
small, but non-trivial lambda.
Fixes #1315.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1319)
> feat: add a `Commit()` helper that takes the `Mutations` directly

- INSTALL.md
- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/etc/kokoro/install/version-config.sh
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/build-dependencies.ps1
- super/external/google-cloud-cpp-common.cmake
- super/external/googleapis.cmake
This updates the version used for the -common and googleapis
dependencies. It also removes (instead of updating) the crc32c
installations, as the library is not used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1326)
> chore: update dependency versions

- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/Dockerfile.ubuntu
Python 2.7 is EOL, and we need Python for cmake-format.
Part of the work for googleapis/google-cloud-cpp-common#194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1332)
> ci: update builds to Python 3

- ci/kokoro/Dockerfile.ubuntu
Part of the work for googleapis/google-cloud-cpp-common#194. Because the CI builds mask errors so easily, I manually rebuilt all the images associated with `ci/kokoro/docker/Dockerfile.*` files, using no caching information.  I really think we are good this time.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1335)
> fix: yet another Python 3 typo

- README.md
- ci/test-readme/generate-readme.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1339)
> fix: use correct quickstart URL

- .clang-tidy
- ci/kokoro/Dockerfile.ubuntu
- ci/kokoro/docker/build.sh
This repository was already using the clang-tidy distributed with
Fedora:30, just changing to Fedora:31 brings it in line with other
repositories (`-common`, `-pubsub`, and `-bigquery`).
Cleanup the ubuntu Dockerfile, removing the formatting tools that we do
not use in any of the builds based on that image.
Part of the work for googleapis/google-cloud-cpp-common#204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1340)
> cleanup: use same clang-tidy in all repositories

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/channel.h
- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/spanner_client.bzl
Factor the `SessionPool::ChannelInfo` struct out to a stand-alone
object, so we can store a `shared_ptr` to it in each `Session`.
This allows us to properly account for `Sessions` that are marked bad or
disassociated from the pool.  Previously, the per-Channel session count
was not being decremented in those cases.
Since the `Channel` also holds a `shared_ptr<Stub>`, we can eliminate
the `Session::stub_` member.
Fixes #1344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1346)
> fix: associate each `Session` with a `Channel`

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
Centralize all Session creation in the `Grow()` method, which computes
the number of Sessions to create on each channel to balance the load
across channels. Also introduces an async mode (not implemented here)
which will eventually become the only mode.
Also fixes a bug where the per-channel session counts were not being
updated properly when `Sessions` were marked bad or disassociated.
Maybe this part should be its own PR, and I don't really like how it
obfuscates the locking requirements so I'm open to suggestions on how
to do this in a cleaner way.
Part of #1172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1343)
> feat: refactor and enhance session creation logic

- ci/kokoro/windows/build-dependencies.ps1
- ci/kokoro/windows/vcpkg-ports/googleapis/CONTROL
- ci/kokoro/windows/vcpkg-ports/googleapis/portfile.cmake
- ci/kokoro/windows/vcpkg-ports/googleapis/usage
Use vcpkg overlays to get the latest release of googleapis. A separate
PR will update the release on the vcpkg repository, but we want to
unblock ourselves to make progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1354)
> ci: update googleapis for Windows+CMake builds

- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool.cc
Assume that the session was used (i.e. a RPC was made) just prior to it
being returned to the pool.
I debated doing this in `Stub()` which would be marginally more accurate,
but would require taking a lock we don't otherwise have to take. Since
our notion of "last use time" is already just an approximation of what
the backend considers "last use time" and the timeframes we care about
are measured in minutes, it didn't seem to be worthwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1353)
> feat: Keep track of the last time a `Session` was used

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1336)
> feat: add ostream operator for Value

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/samples/samples.cc
Use the new `Commit()` helper whenever the mutator ignores the
passed `Transaction` and simply returns a `Mutations` value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1359)
> cleanup: make use of the new Client::Commit(Mutations) overload

- ci/kokoro/docker/build-in-docker-bazel.sh
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
Introducing a new environment variable `RUNS_PER_TEST` for the build script. This is only useful for linux based builds for now, and probably only useful for unit tests.
Example usage:
```bash
RUNS_PER_TEST=10 RUN_INTEGRATION_TESTS=no ci/kokoro/docker/build.sh integration
```
Then bazel or ctest will run each tests 10 times. This is useful when you have flaky unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1360)
> testing: add RUNS_PER_TEST environment variable

- google/cloud/spanner/value.cc
- google/cloud/spanner/value.h
- google/cloud/spanner/value_test.cc
This PR changes the `Value` `op<<` operator for the types `bool`,
`int64_t`, and `double` so that they print by default as they would as
normal C++ types. This also enables them to work with C++ IO stream
manipulators. For example, this change makes the following work:
```cc
std::cout << std::hex << Value(42);  // Output: 2a
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1362)
> feat: Value streaming respects io manipulators

- ci/kokoro/windows/bazel-presubmit.cfg
- ci/kokoro/windows/bazel.cfg
- ci/kokoro/windows/build-bazel-dependencies.ps1
- ci/kokoro/windows/build-bazel.ps1
- ci/kokoro/windows/build-cmake-dependencies.ps1
- ci/kokoro/windows/build-cmake.ps1
- ci/kokoro/windows/build-new.bat
- ci/kokoro/windows/build.ps1
- ci/kokoro/windows/cmake-new-presubmit.cfg
- ci/kokoro/windows/cmake-new.cfg
This is part of the work to have uniform build scripts for Windows
across all the repositories. In this step I copied the build scripts
from -common, and tweak them to build this repository. When there was a
confiict with an existing file I named the new file `-new`. We will need
a few more changes, one to configure Kokoro to use the new
scripts, another to delete the old scripts / replace them with the new
ones, then configure Kokoro to stop using the `-new` placeholders, and
then remove the placeholders.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1367)
> ci: copy windows build scripts from -common

- google/cloud/spanner/client.h
- google/cloud/spanner/results.h
- google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1364)
> docs: updated snippets and samples for profile and analyze methods

- ci/kokoro/windows/build-new.bat
Part of the work for googleapis/google-cloud-cpp-common#231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1369)
> ci: actually use Bazel 2.0 in the build

- ci/kokoro/windows/cmake-presubmit.cfg
- ci/kokoro/windows/cmake.cfg
Part of the work for googleapis/google-cloud-cpp-common#227
This change points Kokoro to the new scripts for the CMake builds, but leaves the old scripts untouched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1372)
> ci: use new CI scripts for Windows+CMake

- google/cloud/spanner/client.h
- google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1374)
> docs: add snippets for Commit() with a mutator or mutations

- google/cloud/spanner/value.cc
- google/cloud/spanner/value_test.cc
Non-printable `Byte` values are now printed using their octal escape sequence. We don't use hex escape sequences because in C++ `"\x41B"` is a 3-digit hex number, not 2-digits.
We might consider escaping non-printable string characters too. I didn't do that here because it's not clear that we want that feature since normal `std::string` objects don't do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1371)
> feat: escape non-printable bytes in Value::op<<

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/backup_integration_test.cc
- google/cloud/spanner/integration_tests/database_admin_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
- google/cloud/spanner/samples/CMakeLists.txt
- google/cloud/spanner/samples/samples.cc
fixes #1376
In `samples.cc`, I put all the Backup related test in the block for instance CRUD test. I also created a new integration test for the Backup feature. The new test also creates a new instance with a random name so the restore operation won't conflict with another test run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1379)
> testing: use a temporary instance for Backup tests

- google/cloud/spanner/bytes.cc
Assert that the execution character set looks like ASCII, as required
by the `kCharToIndexExcessOne[]` lookup table in the base64 decoder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1383)
> fix: the Bytes base64 decoder assumes ASCII execution character set

- google/cloud/spanner/bytes.cc
- google/cloud/spanner/bytes.h
- google/cloud/spanner/bytes_test.cc
- google/cloud/spanner/value.cc
- google/cloud/spanner/value_test.cc
This makes it so that `Value::op<<` can just stream the `Bytes`
directly, and `Value` is no longer responsible for the
formatting/escaping of bytes.
This makes it so that if a user has a `Bytes` object (not a
`Value`), they can still stream it. It's also more efficient this way because we can
directly iterate using the `Bytes::Decoder` rather than having to first copy the
bytes to an unnecessary `vector<unsigned char>`.
There's no change in formatting logic or behavior in this PR. Just a
refactoring/move of the code from value.cc -> bytes.cc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1384)
> refactor: move Bytes formatting to bytes.{h,cc}

- google/cloud/spanner/date.cc
- google/cloud/spanner/date.h
- google/cloud/spanner/date_test.cc
Date was the only non-aggregate "Value" type that didn't already know
how to print itself. Everything else, (bool, int64_t, double,
std::string, Bytes, and Timestamp) were all streamable directly.
`internal/date.h` already had this support, so it just took a little
plumbing to make the user-facing `Date` class to itself also be
streamable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1385)
> feat: taught Date how to stream itself

- google/cloud/spanner/value_test.cc
Adds a unit test that ensures that
```cc
os << t;
```
Produces the same output as
```cc
os << Value(t);
```
for all `T` in `bool`, `std::int64_t`, `double`, `Bytes`, `Date`,
`Timestamp`. This list does not include `std::vector<T>` nor
`std::struct<...>`, because those are not directly streamable on their
own, so there's nothing to compare with.
The other notable exception to this list is `std::string`, which does
not produce the same output since `os << Value(std::string{...})`
wraps the output in double quotes.
Related to #1380 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1387)
> test: add test verifying Value op<< output

- google/cloud/spanner/value.cc
- google/cloud/spanner/value_test.cc
Oops. It looks like we forgot to teach Value::op== how to compare Date
and Timestamps. Now it's fixed, and I added a test to make sure basic
Value equality works for all "kinds".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1386)
> fix: Value::op==() correctly handles Date and Timestamp

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/internal/async_retry_op.h
- google/cloud/spanner/internal/async_retry_unary_rpc.h
- google/cloud/spanner/internal/async_retry_unary_rpc_test.cc
- google/cloud/spanner/spanner_client.bzl
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/spanner_client_unit_tests.bzl
- google/cloud/spanner/testing/mock_completion_queue.h
- google/cloud/spanner/testing/mock_response_reader.h
These are mostly copied from `bigtable` in the `google-cloud-cpp` repo.
We should eventually factor these out to `-common`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1389)
> feat: add async call support classes

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
note #1389 is effectively a DIFFBASE; you only need to review the
changes in `session_pool.{h,cc}` in this PR.
Adds wrappers for Async{BatchCreate,Delete,Get}Session that use the
retry loops from #1389 and returns a future for the result of the call.
These could undoubtably use some tests.
fixes #1365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1390)
> feat: add async calls to `SessionPool`

- google/cloud/spanner/client.h
- google/cloud/spanner/samples/samples.cc
Documented one of the Commit() overloads that lacked an example. Link
an (existing) example for Read(). Consistently use `@par Example` vs.
`@par Example:` (note the colon) for the example paragraph. Move some
examples until after the `@param` section, so all the example paragraphs
appear in the same place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1398)
> doc: small improvements to Client samples

- google/cloud/spanner/CMakeLists.txt
The benchmarks were not declared "tests" so they would not run as
part as the regular CMake builds. We may not have strict testing
criteria for them, but at least we should run them to avoid code rot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1400)
> ci: run benchmarks in CMake-based builds

- bazel/google_cloud_cpp_spanner_deps.bzl
- ci/etc/kokoro/install/version-config.sh
- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/google-cloud-cpp-common/CONTROL
- ci/kokoro/windows/google-cloud-cpp-common/portfile.cmake
- doc/packaging.md
- super/external/google-cloud-cpp-common.cmake
Part of the work for googleapis/google-cloud-cpp-common#248
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1399)
> ci: update builds to use g-c-cpp-common v0.23.0

- google/cloud/spanner/sql_statement_test.cc
- google/cloud/spanner/value.cc
- google/cloud/spanner/value_test.cc
Fixes: #1391
This PR changes the way `Value(string)` streams its values.
Specifically, double quotes are no longer included when streaming scalar
`Value(string)` values. For example: `std::cout << Value("foo")` would
output `foo` (no quotes). This behavior matches that of `std::cout <<
std::string("foo")`.
However, when streaming strings as part of an aggregate type
(std::vector or std::tuple), strings *will be* wrapped in double quotes
so that the contents of the string does not break the
structure/formatting of the printed array/struct itself. Any double
quotes in the string itself will be backslash escaped.
This PR also adds double-quoting to field names in tuples, which are
strings and should therefore also be quoted like other string fields in
aggregates.
--- …
> feat: streaming Value STRING only quotes in aggregates

- doc/testing-resources.md
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/backup_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/pick_instance_config.cc
- google/cloud/spanner/testing/pick_instance_config.h
also increase the timeout for backup_integration_test.
also create a document for Spanner resource rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1403)
> testing: use temporary instances in us-west for integration tests and samples

- google/cloud/spanner/bytes_test.cc
- google/cloud/spanner/client_options_test.cc
- google/cloud/spanner/query_options_test.cc
The build is not actually using Clang-3.8, that fix will come in a
separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1408)
> fix: workaround bugs in clang-3.8

- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
Also enable session creation in the background thread.
I'm planning to change the existing uses of synchronous creation to
async but that requires very substantial test changes. However, I did
run a couple experiments - one *only* using `AsyncBatchCreateSessions()`,
and one with that, and *only* calling `Grow()` from the background
thread (that too some hackery) and all of the integration tests,
benchmarks, and samples passed in both cases. So, I wanted to get this
out for review while I work on making the unit tests function with async
ops.
Part of #1271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1405)
> feat: implement async session creation

- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/database_admin_logging_test.cc
- google/cloud/spanner/internal/database_admin_metadata_test.cc
- google/cloud/spanner/internal/instance_admin_logging_test.cc
- google/cloud/spanner/internal/instance_admin_metadata_test.cc
- google/cloud/spanner/internal/logging_spanner_stub_test.cc
- google/cloud/spanner/internal/metadata_spanner_stub_test.cc
- google/cloud/spanner/internal/time_utils_test.cc
- google/cloud/spanner/results.h
- google/cloud/spanner/row_test.cc
The clang-tidy build is still using clang-8.0, we want to use clang-9.0,
this changes fix a few warnings. In most cases I preferred to use the
recommended fix over silencing the warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1409)
> cleanup: fix clang-tidy-9 warnings

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/doc/spanner-main.dox
- quickstart/README.md
Much of the getting-started and compiling stuff I'm not sending the user
to the quickstart/ repo, which has code and instructions that we're
testing, and I think it's nice and simple.
Moved the info about authentication into the quickstart/README.md.
Added a summary of most of the environment variables that can configure
the library.
Fixes: #1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1404)
> feat: clean up main doxygen page

- BUILD
- google/cloud/spanner/BUILD
Adds user-facing bazel build targets to the project's top-level BUILD
file. This file should list *all* of the BUILD targets that users are
allowed to use. In a future PR, visibility restrictions should prohibit
users from reaching down into `google/cloud/spanner/BUILD`.
This change will make things simpler for users since they'll have a
single, uncomplicated, top-level BUILD file that contains all the build
targets that they're allowed to use. It also gives us a place to put an
`includes = ["."]` directive, which will allow Bazel users to include
our headers using either double quotes or angle brackets.
Related to #1296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cl …
> feat: adds BUILD target to top-level BUILD file

- BUILD
This makes the following command work again
```
bazel build ...
```
from the top-level dir. And users are still able to directly link against the `//:spanner_client` build target.
This fixes an issue that was added in https://github.com/googleapis/google-cloud-cpp-spanner/pull/1396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1419)
> fix: //:spanner_client tagged manual

- BUILD
Using `includes = ["."]` in a top-level BUILD file causes too many odd
behaviors and breakages. For example, it makes `bazel build ...` fail.
The goal was to allow users to include our headers using angle-bracket
includes, which this does. However, there may be a better way to do
this. Until we figure that out, we should remove the odd line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1423)
> fix: remove `includes = ["."]`

- google/cloud/spanner/internal/session.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
- google/cloud/spanner/internal/session_pool_test.cc
- google/cloud/spanner/session_pool_options.h
Call `GetSession()` during `SessionPool::DoBackgroundWork()` for any
session whose last-use time is older than the keep-alive interval.
Also change the type of `SessionPoolOptions::keep_alive_interval_`
from `std::chrono::minutes` to `std::chrono::seconds`.  This allows
the running time of the test to be drastically reduced. It is not
an API breakage because `minutes` convert implicitly to `seconds`.
Fixes #1171.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1425)
> feat!: implement SessionPool session refresh

- ci/kokoro/docker/build.sh
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/backup_integration_test.cc
- google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
- google/cloud/spanner/samples/CMakeLists.txt
- google/cloud/spanner/samples/samples.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/cleanup_stale_instances.cc
- google/cloud/spanner/testing/cleanup_stale_instances.h
- google/cloud/spanner/testing/compiler_supports_regexp.h
- google/cloud/spanner/testing/policies.h
* enable backup related test for the coverage build
* use shorter timeout for admin clients for backup tests
* correctly cleanup stale instances by deleting backups first
Fixes #1432 and fixes #1429
We may still want to disable backup related tests for the coverage build. If so, we can run the backup related tests in nightly build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1438)
> testing: improvements for Backup related tests

- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/integration_tests/session_pool_integration_test.cc
- google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
- google/cloud/spanner/internal/session_pool.h
Make sure the low-level functions to make async calls actually work,
the value of unit tests for these is limited (we would be re-testing
the retry loop, but we have tests for that). An integration test
verifies we are filling the protos with the right data. Note that
some of these functions are not exercised in the other integration
tests because they run too infrequently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1442)
> test: write integration test for SessionPool

- CMakeLists.txt
- ci/kokoro/Dockerfile.centos
- ci/kokoro/Dockerfile.ubuntu
- ci/kokoro/Dockerfile.ubuntu-xenial
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/common.cfg
- ci/kokoro/docker/download-cache.sh
- ci/kokoro/docker/upload-cache.sh
Part of the work for googleapis/google-cloud-cpp-common#263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1446)
> ci: use build cache for ci/kokoro/docker builds

- google/cloud/spanner/integration_tests/session_pool_integration_test.cc
- google/cloud/spanner/internal/connection_impl.cc
- google/cloud/spanner/internal/connection_impl.h
- google/cloud/spanner/internal/session_pool.cc
- google/cloud/spanner/internal/session_pool.h
Change some methods to pass by const-ref rather than value, and
eliminate some `performance-unnecessary-value-param` lint suppressions.
In `PartitionQueryImpl`, I removed a `std::move` that had no effect since
it was already passing via const-ref.
(none of these APIs are public FYI)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1447)
> chore: remove some unncessary NOLINTs

- google/cloud/spanner/keys.h
- google/cloud/spanner/samples/samples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1451)
> docs: add snippets for methods and classes in keys.h

- google/cloud/spanner/integration_tests/client_integration_test.cc
`set_optimizer_version("some-invalid-version")` doesn't faze the
Spanner emulator, so expect the normal result for the query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1453)
> feat: allow for the emulator in ClientIntegrationTest.QueryOptionsWork

- .clang-format
As we prepare to move to a monorepo, we want all of our existing repos
to be formatted with the same .clang-format config. This config removes
any per-library specific names (i.e., I removed "spanner"). Instead,
this names the headers and directories of the *common* headers and
ensures that those sort after the other quoted "google/cloud/.+"
includes, which should be the project ones.
This exact same `.clang-format` file should work in all of our repos.
The intent is that library includes sort first, and they sort before the common includes. For example:
```cc
// file: spanner/foo.h
#include "google/cloud/spanner/blah.h"
#include "google/cloud/bar.h"
...
```
Part of https://github.com/googleapis/google-cloud-cpp/issues/3596
--- …
> fix: made .clang-format generic for any repo

- README.md
- ci/generate-markdown/generate-readme.sh
Part of https://github.com/googleapis/google-cloud-cpp/issues/3591
Preview: https://github.com/devjgm/google-cloud-cpp-spanner/tree/readme-announce
@scotthart I think you'll want to include a blurb like this one in the April release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1455)
> feat: announce move to monorepo

- google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
- google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Do not expect a namespace alias declared within an anonymous namespace
to work outside of the anonymous namespace, as it could be ambiguous in
that context.
Fixes #1461.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1462)
> fix: fully qualify spanner names outside namespace-alias scope

- google/cloud/spanner/value.cc
- google/cloud/spanner/value_test.cc
Always use `TypeCode` when spelling the name of a type-code value,
just like if `TypeCode` was a scoped enum (`enum class`).  This is
a readability aid.  Previously we were inconsistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1463)
> cleanup: treat enum TypeCode elements consistently

- ci/colors.sh
- ci/kokoro/docker/download-cache.sh
- ci/kokoro/docker/upload-cache.sh
- ci/kokoro/gcloud-functions.sh
To upload and download the cache we need to add a service account to the
developer's environment. For the CI builds this does not matter, as the
CI runs with a clean environment. When running the builds locally this
was annoying because it revoked the developer's credentials.
These changes fix that, probably using more changes than strictily
necessary, but it was easier to copy the code from g-c-cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1466)
> ci: avoid modifying the developer's gcloud config

- ci/kokoro/docker/download-cache.sh
- ci/kokoro/docker/upload-cache.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1467)
> cleanup: fix shellcheck warnings

- google/cloud/spanner/CMakeLists.txt
CMake requires target names to be unique, even in different directories.
Fortunately the target name can be different from the binary name,
though it requires a little more work to make it so. Unit tests are more
likely to repeat names, so use a prefix to minimize the possibility of
collisions. The other targets can be handled on a ad-hoc basis when and
if we have a target name collision.
Part of the work for googleapis/google-cloud-cpp#3548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1471)
> cleanup: make unit test target names unique

- google/cloud/spanner/BUILD
- google/cloud/spanner/benchmarks/BUILD
- google/cloud/spanner/integration_tests/BUILD
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/integration_tests/session_pool_integration_test.cc
- google/cloud/spanner/samples/BUILD
Fixes googleapis/google-cloud-cpp#3713
Currently, the `:google_cloud_cpp_testing` target _also_ includes a
`main()`, that is exactly the same as `:gtest_main`. However, that
target is losing its implementation of main (it's gone in `-cpp`
already). So to keep the `-spanner` code working when it moves into
`-cpp`, it should explicitly link with `:gtest_main` now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1472)
> chore: link with gtest_main

- ci/kokoro/Dockerfile.ubuntu-xenial
- google/cloud/spanner/client_test.cc
- google/cloud/spanner/database_admin_connection_test.cc
- google/cloud/spanner/instance_admin_connection_test.cc
- google/cloud/spanner/internal/connection_impl_test.cc
- google/cloud/spanner/internal/log_wrapper_test.cc
- google/cloud/spanner/internal/partial_result_set_resume_test.cc
- google/cloud/spanner/internal/partial_result_set_source_test.cc
- google/cloud/spanner/keys_test.cc
- google/cloud/spanner/mutations_test.cc
- google/cloud/spanner/results_test.cc
- google/cloud/spanner/samples/mock_execute_query.cc
- google/cloud/spanner/sql_statement_test.cc
- google/cloud/spanner/value_test.cc
Fixes googleapis/google-cloud-cpp#3610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1473)
> ci: enable ccache for the clang-3.8 build

- google/cloud/spanner/integration_tests/client_integration_test.cc
The Cloud Spanner SDK emulator now supports `ExecuteBatchDml()` and
(in the imminent release) `PartitionRead()`, so remove the checks that
allowed for `StatusCode::kUnimplemented`.
We currently don't test automatically against the emulator, so this
only affects manual/internal testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1474)
> cleanup: Enable PartitionRead() and ExecuteBatchDml() with emulator

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/benchmarks/CMakeLists.txt
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/samples/CMakeLists.txt
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3976
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1478)
> fix: explicitly set copyright year for bzl files

- .clang-tidy
- google/cloud/spanner/benchmarks/benchmarks_config.cc
This PR installs an exact copy of the .clang-tidy file from `-cpp`. The
only real change is that we now ignore the warning about using C arrays.
So I also removed the one NOLINT warning that's no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1480)
> fix: sync spanner's clang-tidy warnings w/ -cpp

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/benchmarks/CMakeLists.txt
- google/cloud/spanner/testing/pick_instance_config.cc
- google/cloud/spanner/testing/validate_metadata.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1481)
> cleanup: enable clang-tidy for testing and (macro) benchmark libraries

- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/client_integration_test.cc
- google/cloud/spanner/integration_tests/client_stress_test.cc
- google/cloud/spanner/integration_tests/data_types_integration_test.cc
- google/cloud/spanner/integration_tests/session_pool_integration_test.cc
- google/cloud/spanner/spanner_client_testing.bzl
- google/cloud/spanner/testing/database_integration_test.cc
- google/cloud/spanner/testing/database_integration_test.h
This removes our need to define a custom `main()` function only to
create the Environment object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1486)
> refactor: use SetUpTestSuite instead of Environment

- ci/kokoro/Dockerfile.fedora-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/kokoro/windows/vcpkg-ports/googleapis/CONTROL
- ci/kokoro/windows/vcpkg-ports/googleapis/portfile.cmake
- doc/packaging.md
- super/external/googleapis.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1489)
> feat: update cpp-cmakefiles to 0.9.0

- cmake/GoogleCloudCppCommon.cmake
- google/cloud/spanner/CMakeLists.txt
- google/cloud/spanner/integration_tests/CMakeLists.txt
This PR moves some calls to `find_package` into the
GoogleCloudCppCommon.cmake file, because these packages will be changing
location when Spanner moves to -cpp. Moving these into the common file
lets the CMakeLists.txt files in google/cloud/spanner/ compile in this
repo and in -cpp, without modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1488)
> fix: moves find_package calls to common file

- google/cloud/spanner/benchmarks/BUILD
- google/cloud/spanner/benchmarks/CMakeLists.txt
- google/cloud/spanner/integration_tests/BUILD
- google/cloud/spanner/integration_tests/CMakeLists.txt
- google/cloud/spanner/samples/BUILD
- google/cloud/spanner/samples/CMakeLists.txt
This label will be used in `-cpp`. This PR also removes a loop in cmake
that appears to be dead code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1490)
> chore: adds spanner-integration-tests labels

- google/cloud/spanner/internal/connection_impl_test.cc
Fixes: https://github.com/googleapis/google-cloud-cpp-spanner/issues/1392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1491)
> fix: silence benign gmock warnings
